// Code generated by "esc -o static/css.go -pkg static -include=(.+).css -prefix=oldweb/ oldweb/Template"; DO NOT EDIT.

package static

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/Template/skin1.css": {
		name:    "skin1.css",
		local:   "oldweb/Template/skin1.css",
		size:    3459,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/+xXQW7bOhBdW6cgnK0lWHYSfEmrj6RFC3TRRYGuKZGSWFOkQI7juIFP0GXv0Rv0Nu09
ClGSI9Oik7YBGqDlxgDfUG84j0M+B1SA2qI7b5LibFUouRbEzySXKkZnL81IvEkqFaHKB1n7G0agjNGi
vr2fV6woYRRJJYCsRiFO8/E1DYuGLacxElJQm6aDCNYlJUdMowsNlWNdw9bvdz5fLqPIJnShHaMLNqRH
INBb8DFnhYjRh7UGlm8Tb+cFFWaiUSGXAnzNPtIYhfPgooakm8txxfg2Rmj6FnMMTEj0hgkJ25pOZ5pV
ei1mPTJDmiqWz6bfv3z69vXzNPEmfSKXZvSJEJpJhYFJsS9ZhVXBRLe5GF0YZbrJZktNXsM5U6MubucF
At+kWLl2wpmgfknbJeG5mXt0Zo7SGU6bcHFEFw5quekySCUngwz2x92VwUiLRFEUXV09zxY5hA4bxG6D
YYscrhs2yHJ5qkFs1GoQGz5okB7ceQEw4HRc0FPq7T/vUo9TAKp8XeOMiSJG82BBK+tcZVQAVUcn9dKw
H0scOiUO3RKHLonDp5VYS86escL6n8S/LbH7mfvDCmeysuSNakgmPyHlUDKT4l/SgJEZLnls1JLHhg/k
6UFv5+GYM7FyvdIPv8hrQahq+sd2J/cOZMymtLYkMQmU8oaqX8+gLWDzoRumGVDyJJvZeUEtNXh3fQXN
mWiFRGdXZjzq5R557mtMiLmUzof2qfdZi//M7EYq4qeK4lWMzI+POW9dDhP12pXZ/2a0cVwWfeiJyPev
r9+9ilF02fk2Lot0DSDF6WXHDqgpy/X5i3niDQ9CazwTZF0A6PDO7UxjKon5B6IzJTlPsfJznNGOYO+w
EEL3AVgpuekjcjOsCF1i8kBIyYqSD9prPGpJHo4hWK0eQQgKZ6s+onebux8BAAD//0sMbriDDQAA
`,
	},

	"/Template/skin10.css": {
		name:    "skin10.css",
		local:   "oldweb/Template/skin10.css",
		size:    1218,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/6yT0W7TMBSG7/0UVnu7TMlSkGZfbRS0SUhMExLXTnyamjk+kX1S0kV9Ai55D96At4H3
QM7WVRmgVnQ5d5a//J9+26cWq6IlQsd6VqDX4AXPmo4HtEbz6WUaRxaqvKs8tk4nJVr0gk8v0jiSLdBR
slC1sWsxuVFWkXHI3xuHtG5gchJMHVp3Mvn1/evPH98mkg9AMPcgeHbWdJJb4yBZgqmWJHj2qukk2zAW
zYxrWmI9u/xwO397+xS6E5Ts0/X845Xg5+kDFinWj6T4IVZsZzVIMYKOEmVN5YSFBUk2tpxtLUkVx+bN
Ds17qP6p+Rg/VwRXoDT44y1or8XruGdgvjwuFWi15H8zq8MLHMRY6XMbyCzWz63yP6wc+lrZnVc+fIMX
O73BQO8Q6fjKnl8U7mP8EFOgXvN+XMuGXQhr3N12+U0aRw4/0FCiV2TQCYcOZNn6gF4sldMRW5lgCPSW
fHyVh5CqJLOC/wCXuAK/h2udBh8PYwwzNq2B9w0GM2xTRUDbEkgeL5XI0lwSNmKW5ZLfJ9dOQyfSDZsW
Fqt/Y3meDlh2dr7Dss3vAAAA//9XiFnWwgQAAA==
`,
	},

	"/Template/skin11.css": {
		name:    "skin11.css",
		local:   "oldweb/Template/skin11.css",
		size:    1980,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/5xVUW7jNhD95ykG0Me2QOxIUZxuyK/Y3mDz1WJRoN+USEtcU6RAUomzgk/Qz96jN+ht
2nsUpGTLcuyssRJgwJx5897McEZTqYuscU4r1KJMG8YNhqTegNVSMIjmsX9JRvN1YXSj2CTXUhsM0cP9
4uPykaCVVm6yopWQr/i/v//895+/CIQzK75xDMlNvSEgheKTkouidBiSWb0hwaWLFT3E/iVoi5DXI1Td
ONSi+a9flp++eKpgH2QR9MfT8vfPGO7jeuNhHoXakRTotaBBS5CCHN+4CZWiUFjylSNorO22i4imjmYX
hLy9NOSJVJfU8c+cMm7OEX0n8F3tejEv/VGmJSMwCAQMSeIb0PHDQd+ChMpeVjc30vK1sU6sXo/lpG/k
KG0qKnfsOErD02X/m7buUWt3Pvt3OgfGE4RAmWav0KLhhuIoDg85VYYDItgxXT1zw6iiV0CNoJK8rZXN
jZYyo2ayojnfj8COZzDbkjL9sndIb2a/3M8IwIFLKYpSevXHXgc+KRt7vCVi1KyPyN46OUPz9Tt2asxJ
sVuEHrAUat32fVvE/iWhAYzn2lAntMJKK07yxlhtcEkV26IH/CyscJztkP3+uARJcyee+Q8AS/3MzXdw
jWLc+Os6BiMUVRzaWlsR3GhmtWwcJ+DnDSdxSpyu8W2SEvg2eVKMb3C8RVEmdXEelqZxgCU39wMs8Ze+
5JRBC6MFmQ7ziSF6DA+B/TKOZvOPt4s5Obzh0Bj504fp9PqpogW313YtVPebJNey8izTr3Xx4ed9nIl1
r5L7uWEFJ9AfOl1PXgRzZdj5g3OYrpGlN2TaOV2dxPjMR4bDcc25ctx0g9/5G9MOOTJqS87Cgo8Wi+X8
06x3DWVGvr8rqV8w0MZpgmrKmFAFhiTs/4qaQigM4c9uG6WzOKjborA3qOH0CsKX5Qoslzx30F60DfYJ
7jp0d7dY+A7BcW27b9P+9Fxxjwt1vujonapvAf0fAAD///EjSjK8BwAA
`,
	},

	"/Template/skin12.css": {
		name:    "skin12.css",
		local:   "oldweb/Template/skin12.css",
		size:    2016,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/5xVTW7zNhDd8xQDGN9OCqTYKRpy5dYOklWLoGjXlDiSWNOkQFH+ieETdNl79Aa9TXuP
grQsW67jBJFW4sybeXzzoztlyqx1zmiyI5mxAi2FtN5AY5QUMErCwzKeL0prWi3i3ChjKYzyxL+MFEa7
uOBLqbb037/++OfvPxmEs0a+IYX0vt4wUFJjXKEsK0chfag3LLgcYo2miX8Z2RPi+Uhdt47syA8/vc7m
rxQ6+4kWI7+9zH559sGTeuNxHkZ2Ay7QkSEnMoELcbhxMVey1FRh4RgZkpscIpI7x7NPhJx8NuSVu864
w2fkAu17iT4I/F3tOjLr7igzSjA4EQQKaeorcMgPXs3HH7+fPTESKPxsGvdkjPs/hRKNLSWP4Fe0gmse
wdRKriJ4RrVCJ3MeQcN1EzdoZRFdkSa5kAas5xiunhmxhR1pcmuUyriNC55j31pFeNiZuam4MOveoetK
gDOXSpaV8gkuvc58xuIjD8Ht4nqyMydneb7o7fOH+WQ+Obdza6+S3RMypUrqxa5rhm6GgkYCc2O5k0ZT
bTSyvLWNsbTiWuzJlK5kIx2KLyB57uQKvwCszArtETedhltc4lot0PqmHIIJGS0RdrVpZHDjWWNU65CB
b2OaJmPmTE0n6ZjBW/yiBW5osiejTJnyfdh4nARYev94gqW+jSvkAnZkuHccA3LJN8wHuSxNGIVD7kvb
IGbSz9vXpoT1K3aJQrZL8LKfUp3Pyu9t42SxPSJi2438aTXPZ/PHedI7ZMY5s7zq4etYKLOmwFtnGKm5
EFKX4UIbRpbcllJTCB/9bkmSbwzIWyyDyg9eIs+PW+QRhBUdQYMKcweDzQHH7RWtjpJwLwmDI9OLPwhA
b2ncViHtlnx/6kwdr6VwVbjc6dz3xLlhINVVxEGjoWkPpGsgtLfLP75R/ttV95huN9/ugOF6v0++vdMU
XQWDBBQOf8HjWdcp/pDs/wsAAP//dvaBZeAHAAA=
`,
	},

	"/Template/skin13.css": {
		name:    "skin13.css",
		local:   "oldweb/Template/skin13.css",
		size:    1966,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/6RUUY7jNgz9rk5BYFBgF4gzSWcHRSX0Y4uZYverxaJo+8tYsq2NLBoSnUk2yAn62Xv0
Br1Ne49CjpPY3qAzRS0giMRH6ZF8JEpn/Rr2wGbLmTY5BWRLXnryRkFOjoK8WXSfOgiUmLPdmP/gsLHR
stHPedx1X+dR0caEK/jWaxOc/dwJ8jZECjIPFGOFNsBBiBXp3R7EFzEP5NwKQ1ZgbrLesyiKAlENzRgC
PWXjAAQAXBCxQn2B4NdpTSCVLStny4r/FXWnn8doDOsXPMgB8/UwqqJQIkFWmK/LQK3XU+vYaGssjWyD
ezWf375Pm3gb19Yff5d3t4WjJxPmH5vy9dS3oWi70qyImWoIKaopKJjGIEtP/b+pHZkxr2rjWRZ2a3Sy
J0hBnrMCa+t2cmOCRo8zwGDRzYCxohrVGRbtJyOXy2bbHSWNZJVJZOTyvj8cFfYgBOt5bpyLYi9WFLQJ
Ejr/42aqg/408s4ZGclZrcT1DCdVfcqs12Yrl0oU1rEJUjSBSqul/rXLNwf0saBQz2ubVEsFz9E1Fb6i
BnPLu2/vF6+TiueOylXLTH7MEzoOcOL3GRW4yRdpKTFM499//PbXn7+rQc5g+VWzVaOMQZeyDtKH9XaR
lhI9H+ublsVefPfDh4fHDxJ6+4WWEr+8f/jpXbp8kVJ66NzEfsQFejJiUMDERXRtj86WXjpTsBJjcm+O
N4o54+oFV7556ZVXYv2RIn9PxCZMHyoNhdLiDH4+CfPtUZjvjNsYtjnOIKKPWTTBFrMTrwGPU6+kdyqD
GvZiXBVWIE617KsMHXrlqIT91CZuhu6LhtX/YazOWquNtm0NaVZf3hrG8bGNbIvduUVCn9SLRh8fHr95
vPTQcVZcRaTBn8aNBGyZlGhQa+vLLqCtEjWG0noJ3eZcvcXiSwXnlrtPOUr8MBicQafVGUTjTM4wqiJI
mIyVU3uMZ8C5lQBgPAd6tZ9PmZrsyWqujqPkfJ40NzSMUnXV45ijsekA4p8AAAD//6tVYMiuBwAA
`,
	},

	"/Template/skin14.css": {
		name:    "skin14.css",
		local:   "oldweb/Template/skin14.css",
		size:    1765,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/7xVvW7cOBCul08xsHGdZPjvjDup8t36YDf2YbG4SzsSZyUiXFKguN51BNcpgqQJkDdI
mzZV3ib2cwSk/tcLx1VYiTOc4TffzEcdSJ0lK2u1YhVLtOFkIjgqNlBqKTjsn/gVJ5i+zoxeKR6mWmoT
wf6ZXzFbaGXDBS6FvIsevrz7/u1jDN5WijcUwdFxsYlBCkVhTiLLbQRHvxeb2B+pc+2nfsXsnjGHR6hi
ZVnF/rqZTS9mUQuihxWz/6+m80uX/LDYuDgXxqoRFmjAsB6Mx8IsbWyIUmQqkrSwMRuDO60zsgOLyQtS
nr405Y5aE6kzqNjkKYUB7D28//D46W293ev2j5+/NvuSjFj4D1Rl2O3mYkklXNMaZnqJai9u0jfd8FAm
bQ+b7rLJoACoK/AAc0IOFRu308ZQF8wp1Qat0CpKtORtiV1a8Dn+1aX9R2tLZpvNjLTJBAbwHxmOCgM4
NwJlAJckb8mKFAPoiwte0E8wjvGa3ClauiTkT+9tE/2ka2eFbS5bNyZfJfQAoB3vunIYMNrRRwaqbWKG
hJ4cdtc84eU5OuqYBlOnXJsLBUor6u8aF3V8+NtOxgrkXKgsdEREUMuqtZk61hldWYnmd25qy9RoKRM0
IRqj162Y23dh4E+wpNb9h18j9wLTzv2nXyN3LrJcOgjPnClz5D2E7kD/bA2MO2Yh+KVqc8OBFZvML17N
w+nF3zez8/nVzXXk+rbj+D3DKNe3ZKrWt6XbgQ5hpTgZ13JwEe7Dq8E6GU+G7zvHMifeP+PuEG0sGsIA
/AscQEmSUgsj+UDH2W2rWnRjGkMzhNs/CIDOU9o7SVFzdR9gdRGuBbe5R9bb3SwOHa3dz+POiERbq5dj
1z2wHwEAAP//2Wp6vuUGAAA=
`,
	},

	"/Template/skin15.css": {
		name:    "skin15.css",
		local:   "oldweb/Template/skin15.css",
		size:    7569,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/9xZ207jRhi+Xj/FSFZFK2HWjgkB+8pLQrBqYhS8u6U3yIeJM8KZsZwJm13EE/SyUh+j
6gv0bdo+RzVjOz7EOUGoUBPtgg8z83//8ft/zKs+eBTefbCH3d5Qcuxr6bPZdS41IMdzHWS3rd6F03T/
g+049lXTk6HZvywvEZ6ES+fKYkdNEJa+oICONdDpnPBHH+zu7Ropro1u1xz0001r95hoG4S9sAeOdGP+
3NOA0uIvGuc/9of2x0FXA7Mk+v49mrghnL6f3iOc/q+033vhXUDoUYhGPwDRV9gXRHBEASXxOgXkgqWP
sptXxrBvDrKLc9uyhxoQVVXVgWUOetJlL0WmtOXvih0c+7qM4MK4Mq1bDRxYMx8FLugnLg7gwWF+fePi
KfiIkU/43b9//+WvP389ODz457c/8t/dBLnR4QNMAhe7h1MXT6UpTNBIB07vJ0cyLLM/0IAPMYXJOlMK
RxEJvRmlBAuPgkeSACYaUOI5mJIIBUCU+Uf3XP8+TMgMB5JPIpJoQPR9XxdGBFNp5E5Q9FVLZdMBvzdF
32BupQhhKI0hCseUaSae6/yVdCPRldlXz4VBOJ5R4VFIZdZA9ryQSRcyBIrMVCo88WXCY0UWkAkjFMJw
WQQK51RyIxRijfmALlSFO053FIzXc+KXONyyQ602raFFCN8zHLmbnsiu0jnLXKTbO7eHhmPaAw1ggiFf
8YCmiMJgt0Vj8gCT8hLVdYMObFgywwFMmMKZ0fwIuokbRXyl1TOGGvAIHeuga95cW8bt4gSRkpi9tK3e
t8wJlMRZThiNRgATKYExdGkpNayxR3agO6NEB5naeQ4sksLJycni7Uzk9PVlI+ZZo8U9uhLCTBqmg5jE
aBLuWw3prrKSKqLQQcLCgZmDksk2fplpQJXVZi+tAbywbMPR0lNYuIkRCcnbjLg815wdr0fWaa+JRn0r
YzAlbPDITHFp5noSRC8iIXYn8E3rrqUu5y6lXdGeui6XVf0FNJa4B5hQ5LtRltoXlS8NRvGCf/QSfzhm
G/Prz5kMHokCnvvFCQqCCCqvkHOynUtWfmm22S7BNGUU9nMC8WwHmGX328H+coUsjUajJhG/SQgHcK7J
ekW4j1bJtzPxJjBAswkvD83+XYTCipdLmDbDKIVGbbtNyaESPLW1lnnjSDfOrdWTnNvrXlHtFtAtc5Vp
FhXSi4h/X4elqlu7ZITu8uPqJUCO580K4pTO/tQbXlj2Zw2MURBAXEPfWjhdnTEsQjLjFWVKr8S0ISSr
xLqVcb6Kmoz/oaKWMBY8q0FHzwMhdlzf68AmMKVo5TkRE8qrTKV05wHQ7mRWEY6YOEprhZSlfokxQIpo
BNOXNyegVnvRP1U3LXtQexeD8uPr1lSYBpQd+7+cI1c9dZkLnWY9Vwpc3SPw1lsCLq8AfsSaL+Z9j8K7
/yRc2Xkc56tlsaw9LptCjumKnMXx71Bu19rhlF1sNXOoF/9ceCb4Qqq0ztYEO10WLA2xumTKhlaVP6+c
KogemXNHXOr/9sm50CS888j8+PmdHr9opF6rm4HTtAMvIFZYTJ2hZ+CrrOpNDBcaOUoBU5Hb60cQhQKe
y2Xk/eS11m7stZ1WwVVqWe4/6liNF6BtyPTbt6kySwEbmPZKulFBUNCNuswvoB9fNpho49CpPEHKG7XW
KzRqxx6Zl3JGKqj09XW7tFq7IJ75Z9BtlyafxRxFWdXWCUejBEEc5LO/vfEGL7ybhgmEeDFLL9Lnc1yx
XZkLdfJ8QSmZvGpF8FhBYKfssQnPUfq+v+vITz1bmVEE0Sfx13To8TwPr6p9E6ZPvaFjnhtWLkgaXXWs
VcqhbuXdFVunDKIZ8dE1mdILQmiaeVZwr9IMvxghhmS3MXEpCs4YY9tJb1VX77QqXnDaOWmp8toxqFJX
AcfBYPgLTrS/8lEO+ONtuAAoeoF6Rq4SZHmNKeMxoWR5eMP/AncKy1mthrRVH+GsWZK1SEtD5Wa+vwQR
Tti/2ohnzXFFW1DP1fU1wpPwbwAAAP//F+k5v5EdAAA=
`,
	},

	"/Template/skin16.css": {
		name:    "skin16.css",
		local:   "oldweb/Template/skin16.css",
		size:    1178,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/4xTUY7aMBD9rk8xAq3USgQlEGjliA9K0iUSIhWk6rZ/gTjBWmNHiWGzRZygn71Hb9Db
tPeo7LAlUHaF5yPSzJvn9zyT0IUdevUhmIbG3P/qYbA6WenAKJgEMwxNUx+0R/7046fwOujcm3ijK7Gh
2+bRVmP9SejNMLi5yOarKBYPr2EkmMgHzUSfFgRJcjew9PfLwHpzbB8qglNuB0LvLjRcbxTMhqEfTDFw
wUmtB6/EluT/d6I9yqwL6lW+c9HVxJ96xtjzb8chBssybxS0ew61Kwr7Qv6coltR9K647V0F7SvoSaVj
V5W3dYe2afftzjlHTyPbkpSyDu4uVZyDO+aNU9OkRElHta8J36j2LIpjylMMlpmVzhOxddH2y1dV3tor
EsWqOxFcGgX9RlRJUVeZJFpT9ojhlog8pVELGiFdkwKm5AFmYh3xRgt0pgUFyWnSgsafn99///rReGIo
5CMjGBaCxUrvEDPK7y8uxhBvaUEliZ+pPr9SbSbSxUZKwdEOLUQekxyDlZVQCEbjf1u7iJb3aS42PDaW
avkxNJemCgfVzVYGHKg/iV4ORjkxVoSmK6kGm5WOhlRczaGpQnnUeijPNhLt0Ptg5qpf71A/ynLQZ98N
x3rqh1kykaLdiRY4iEFHMVoLUmM3IkZTjhlJpINOxdkHRv36PdjVvfSzcv83AAD//+fUgXqaBAAA
`,
	},

	"/Template/skin17.css": {
		name:    "skin17.css",
		local:   "oldweb/Template/skin17.css",
		size:    916,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/7STsW6zMBDHZ/spTsnyfQMEqihNzNQMlfoYBg5wY3zIXCpSlHeviBUlUumU9gaGO/H7
nf+WtRBiZBw4KrEgr9mQU+DIYXaWWlnjDhBqBKjIcVTp1tiTghdvtM2g55PFLIx684kK0nU3ZFCQJa9g
uUk2yW6XgUVm9FHf6cK4WiXdMPEb+kD/CH6bbJOqmsfnVJ4AbutLMWeQ4ieHFFdLcqmp892TSZHr4lB7
OrpSHb39t4jj1Vura+xX/cG48E2fV3kdv3f14j84ijx2qBkqM2AJOTFTC97UDWfyLCXr3CI8Fvx157lk
uASAP+RL47ojj1Lk5Ev0ihvjYLlf79evG0i7AXqyppzyvItuWV0qBIADa4/6AUTjRykanDJVT9M1TWe9
Lh84oXf7P5odB394ExM4Lqht0XEP94r09xRfAQAA//9g6R99lAMAAA==
`,
	},

	"/Template/skin18.css": {
		name:    "skin18.css",
		local:   "oldweb/Template/skin18.css",
		size:    10670,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/9RZ7W6jPBb+vbkK1FevOiOViiSk+aj6I01oG03aRISZzuw/A06CSnBknKbVqlewP/c+
9g72bnbvY2XzZcBASuadD/hRFc55eM6xfc5j59x0d7Ap/aPxt5vZgyEvJn/XBlKztX25lEaz6UwfSH8o
itoD4FKaTh40+U6b3N4ZzIRcSsznZng/mX4bSCcGWKMNODmTTv7373/+9z//Omm8NRh+qxS/rV50etYx
+O1S/FZfVTu9Y/DVUvyLTrfdhcfgdyry322Z7WPwL0rxOxa9j8HvluN3VbXXPQa/V4pv9S5sRamLv8Lg
tXz+dxV6H4NfMf8hvevibwDGyCuPQFXbZrt13BfKYwD9nlU/R6azyqKrFD2F1lLoo8PQWtVwzd6BcL7t
rBySAewf4HwpLZFHZAu5CNMywS6K6CG8AS59Kcxpmmbn0BzuCEGeEJDPIDV1vO2OOMz2eqaPNV3WA4M/
IIQdG0rK9kXykevYl1JoYMzmwte5HIf2U+1GjJedkqH99cwwZvdiBsPRp1t99vlhLEfOgVEciolegCAY
hV1SsyCY/Otc4tLBFOLF5AUWefJLdvHkTQF5S6F3Ifn86wryhXgxeYGFgHx/2YY2T94SZd5sgY5VnPnc
66rMF+Elmc9b5Mlb0DbTmbcF5LvLvm32C8nnX1eQL8SLyQssyqaNvwaM981kamj6QBpjtF2sgY32H0a0
1lz12XUmzZbLr1dt9vcb/TtHvkOcZ3j1Cv2Pl9Los76g0GvgcQuz36dzuPHWGA6eHd8hkH0rXrZKtw3M
S8nQvhryWBvN9KExmT0MJA95kDkBi36C9wkQy3zW6Bni97m4jvfEewRLr8SDCQniEBfWiotzrxEh5/3+
WDnnfNStXqdZ7gusp6PCjv3rxR271wocWE8FgVf5Ut11RNyJe52wE+8aUSfO2ajbS3qX+W6gtxMFXJ0v
5lknVuZYI0zm995xZcUP7UvLX5NdYflrhuWveWD548osAaYLuQZhzOby42Rs3A1oqU6VedHzoLxHbxTu
Des03Av6Ndt5diyYkW8XvMQ2u/RuvDWuZ+NvjFbSJOazxSTIkwuXRCJoK2pLib2uzbWhMZAw3EJA5KyW
DQTmmfQFYht4gJe0orbKrsZbwxheT7WKrWwwvId9jUKOvy9evnH0++324RBlLUmw7L4feOECqw2982yI
XYfh3+kiCcquYgla9DpSnEXvE8WZs4h3PWxRTB7mn42DtPF8OB5PHm4jC34ZFunlyCVg24z3c+E0Yw8i
m4hx8xBdnZ2bEQgjki8QxWK+3mqMCxgd8KGuDX/K5iKbhB8T8kKbaiMjWzGa9StG+efuknPHx3DimsjN
pKsX1PcNcLxsQ4mGI9DrhcMRvlaKFlrePWwt3YueaLoJ8ARBXtCbMrfQZgM9IhP4QqpSS+3XzmrtOqs1
4aoVhnZFBTrfghWU1xDYQZmLuvuti/Yf2BHK1SmTg6dn0oJg6K3I+uq0ffoxjrapKH9yFURR/szCJsW/
fMxa7CQjYrDFaOXYg/HXyQasoIGB5y8R3pzfOxZGPlqSc8aRhv8xpSNKVEyaFdc4fi1icdP5WbTyM8Tf
mdwk4WkFp2qCWnXYVGrlplKKmnBeLREiAZOizmgDfx2cl/iODU3AjL9oujEZDafycDq5fRgEci36dI8p
xce7iaHJi/lwpNHI9hhsEw6qoiRFxUQvBZjMYucSh3JNSwd6pV7L1g5jyB1Ipgc77Vk9UB50KVL8j8z2
MxXgwQFpqUxI0hnAWsgjIWtWqoALPRtgOUxK6pkNXumzjFRQ+T4fFFRV1PrV1C8+IdNUa2cWLDHhEFjQ
IxCnOLzCYAYcSEKQrFJe0fC8m9cewicbvPq/IjeCwpHLdU2qrblpkZOBak4GlvhUjX225+aAqidHvhHn
QKpysXb8ymyINXFpMoSauEYuMuqvVipCDGEmhnEqcvu46iOd2LXWgVDsffhRR6ooUvkUlqXifVY0Dcrb
SclOK2NQXENFom+/dgjPNanamc2Skt0ttURjChV6Z+p2BM1V7jR4qJcjOxMRgjalujNpZ1RnVOb4wL1s
nJ34V4/jN7gcxyS3ot+3lvQuqgYRQqb5RY8x2hcopKBK86CY6nTeeY+wTcXG908hu6pT+DjTx/K1rg0/
DSQTQ/AkA9c95OiAOT7qw3nkR0Ph9i+/y9pL6CZThEk1uDEhll3HJwWzJtmyrbBjH7MOlIozHeU9Zzol
sYY8ZWIXU1X+6uMnhV+dMaN4df5kUuLfv0vrQxRDJPt/mxDiakR7u4tW6EccSkb7ro4iPJoTVPBg6xHp
D/EYbKDv021V1aHJCoNXzv53KVIJ3dxKKW//nCPXvrjNddD9t8gn5HWb5C99oM720xBga42hv3PjFsg/
S1dP6PvQIw5wuZ0h/yxtvYCefR8w5T8e/MqRepv/PcHumSZo5e0EorPINKcwzW6/3VUbb43/BwAA//+y
6IqBrikAAA==
`,
	},

	"/Template/skin19.css": {
		name:    "skin19.css",
		local:   "oldweb/Template/skin19.css",
		size:    5150,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/+xY3XKaQBi9Dk+xY2+DA6Im4kUGBSMT4mbWbdP0DnFVprBkAmbSdvIEvex79A36Nu17
dAB/FiSRaNZpO13v2G/P+X7OgR07UL8BX4SjHhxgcWh+MFQg124f2iB50NMuTetGBe/I3dim9jHA9izw
7WNQ+fX9688f3yrCo4D1/c5f7XdcUz2XfizE6EILIhW8mUxaLUVpA8scGGLfMM/7WAU1KQ7Bxnss6kYX
Ig2bcKACGlCSoN67oRuR8esDz4J7crcF1nEk6UWw1Tmltk/GMuCW+ZKimQeWWWCnflp/Ivf0DL6xjBjz
zre9MmTF8+XN+UQPedMWakMuqY1dSE+eVckrV3gC9lT/LqQyLx/IgM+r54BWlgGv15ET+D6hkRiRh6iE
iYRHIXOitOk3D5Z3LtOI2iFtUCsjHA6cZcTEgfbgjldWZNcLrFHgjZdYKX+9yEHbgXOD44CfHxIHiuxA
ShOkM9pKYJd4WTHx9Vy40iwqK3MbrJydnVUYiMZLa2m1ms0NvS3VtYviGjsKg0siOyqISy57SW3/TFw6
Jg8xfbbIdOt2HiVaHXYRtKyOhsSe1jXEZaiUrDboQKQbSLSMHhbzvVrsdSDG8HJjdw3cN8/7VlwHExMv
NmbY13R4vRGwbkq82AOKnoXMJYzh1TMZaQgxZE6y2H2MtO7FBvR6X9fQRS7jFb/WvThH8O1AzxTTbK5S
Q7lWLGYiCFUvmCaD+fPn8lfOYaKQU0d6dg5t4eja1HFfBbIUf4Fjr4TEI85/sxxoSCOl1ZCdbWaJrTKa
R1FA47EU9z1juo2+p7v5lhU2ZAH04lyTc8LRJKCROLF91/ukpn/ctEHyLHQ/k+UNwXMpEWfEnc4iFciN
VHpC1Q+n4Xzku9G/XGZ1SOj4koShPSXs56ohxb98wPqusS2OuQpsC119qZmyhMffAQAA//++/M1RHhQA
AA==
`,
	},

	"/Template/skin2.css": {
		name:    "skin2.css",
		local:   "oldweb/Template/skin2.css",
		size:    2608,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/6xVSW7jOBTd8xQf9tYKZCt2YnGVsRMgDQeBgV5TIiURpkmBoqcYOUEv+x59g7pN1T0K
pCXZiadyEq0k8fHzv4HkVSi4HKElGDY3HmWx0sRwJUOQSjIMKFZC6VBpIlOG4Q1dhVNecMPoSXNIbPiU
nTQlU1Omj85o3rsHo4jEo1SriaTeagSaffdgFE90YX8UM0+zgr+6Bc4yEaVoWdVp5DxNF42ddYLA930f
I/SGIkUXaAmJksZLyJiLRQiNZyKI4VLBE5fKLHLWaBV8XExkqxppQcE0T1qNX///+/PHfw1c9w9NWzsI
AANyVWeMp5mxLPWYiOqv7TqEfm4wIMo1i1dSCKNtpZKfVQqjItZKiIhoLyExW5GAEJrn544FbAAynmbC
LrdG+f4WKqDHMUVGqJodhFCiR3tgGyijSTw6WIdovVFinRhk6EdniOZOwrXU/f7NDUY5oZTLNAT/vb5t
/6ybG/zeiEgJyjRGkdKUaTvnDSEu84lpOcWJZuSbIrHZSief452JqNikmi0wWOJnQqXRxBgl0bJus53P
oVCCU2heuWdXtEv10Gbzq34wfMyd4JJ5WdlLu2vbK9d2YqAluh683N69eC+Pfz0MQ2he+pd+kqwbwRVg
OHg+NPx0d39w+vVgOBz8vQOB/nm8HT5YG6vmxoRLyqdoCbkquNszJCqUmBh7ghiVhzYBgiXGvcw4NVnY
v7DvJdOu+3j1uKRsHnYw1OFpQ611J59DqpWasjpjgL4ciM+cEGWCXSoyRijTh+l3av7BZbtWoNvdVGCv
ALhSwIuUMWr8LnS9XrlzS4hbxAEoKTK2RlQAvWLV2SpRAWy/O1ZA33kYl1cGbB8BW9vTYDQlgqfSjlv6
GJWfMZOG6ZUJkVDpfgvsFZcINQuBTIzCzpKLnZYEm5ac93rHPanlsvfllph/akd7rx2HPP+yJR8dOTn8
Bafss7pfBOvDoOOfqvtRZfcLd1z778/6icr+DgAA//+9i6s9MAoAAA==
`,
	},

	"/Template/skin20.css": {
		name:    "skin20.css",
		local:   "oldweb/Template/skin20.css",
		size:    1669,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/8RUQY+bPBA9418x2r183wECVU/mVKmH7r1SzwYP4MbxoPFkQzbKf68MidJuaS9ttiAh
4DHzHu+NbbR3YQvLcQLoKEjemZ3zRw0f2BlfQ5Sjx3qBontBDdX7caqhJU+s4bHruq5ta/AogpzH0bQu
9Locp1pwktxiS2zEUdD7YJG9C3hWRj+76ATtvyEf6Bn5T4nLcpUYfsdcxLe1PNCV9q39vjHf0+x11sJT
78K4FzgplX15+vj5k4aqTAXqrFRD9ghwc0Jla6pU9itdKnvth8pWtKmsMe22Z9oHq/fs/3sois3TzvQY
N3HrwnJ9V26q4uvYP/wPj1WTTgiUM45oBDo3oYWGRGgH7PpBapXFlsn7xnDemIj5ouVS+wNsmOlwxS9S
0/+LaTzCvSbhrMQCwB37qznbk8oaYousZXDhWgHVOEEk72xK5bsAbgb9FF6yBCcxjOavNh34pLIBU2y6
SgOR/Hj14fzu1jFfhRdFkIZ7DrBoabfDIBHuRVFEMcxHdVIjRTcvLdNE8nvBlEknl62OxuXm4KwMuirn
NQZXQdX89JK7YHHSeVVD2oUa550cNcSBDrU6fwsAAP//o2w5/oUGAAA=
`,
	},

	"/Template/skin21.css": {
		name:    "skin21.css",
		local:   "oldweb/Template/skin21.css",
		size:    1421,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/8SSTW7TQBTH15lTPIm1rXwQGs+sXJsI9pVYj2cm9ijjedbzJE2JegKW3IMbcBu4B3Lc
0Ca0xFKF8HL0e/8vOeXO+jXbQzC7EGmjkGSw6Dl49EaAQofEs3GWJ28FqA21SFwRtm0lLQm4Zynf2tYG
o18nIlWwW/MaDZbGxaA2yTJNs/yFIHExtM8lmWGNLqlUuDX0ssgKfYhujS2rwKFAp4+6y0U2myaHXQrU
d8D2PbuStXV3HG5khbUUrKfhzVW2WKQzAcyZEAxFbSOV9SWHcTxpgmAnRh6plk5A/9raz4ZD0lGHlNLZ
0nNlfDAkWKsInSskRSupTHT0Wx4+wUYjeCQqW1aus/iN5fM8fZ8IgFNwpk+xZ9XaSmq8PZc6ZSTRJSSQ
VOu/O2lJ6zO3I3fPgu7GZ/9n/SdPzqxCl4fFDkvrm01gezYqkLQhHirru9DXi6trmDQ7aNFZLYCNPn3M
bz5wSN41u+66Oy42IaAfdF1ItS4JN17zx+meTvHz25cf378+/Mh9l8m02Qlw1puoeqg8mffuLJZaK6xr
4wMcOpyH6JccEOKP6Y9Np/PxM2bdkJKM/Jd+vwIAAP//oz0PLo0FAAA=
`,
	},

	"/Template/skin22.css": {
		name:    "skin22.css",
		local:   "oldweb/Template/skin22.css",
		size:    8625,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/7RZXW7juhV+rldBzOACd4Brj+T/kdEHOXYSYzRWICtNpy+FbFE2G0kUZLpJ5uKuoI/d
R3fQ3bT7KERREklRjpz0SsAgIx6eP56fj8dze/Ed/Nr5w7W9drub1V+WBtD7yfMMXNmW7Rjg44A+M2Ct
1svu7XJ1c+saQB9pP3V+67iLN28137fTXf7Z7S6WV7Zjuit7bYAYx7DzW6cX4j2KkxPp/NrZ4tSHqQH0
5BkccYh88NGkz6zzsFq4twb4Mk6eZ2zX9kQIjs9v23q7x32KT7Hf3eEQpwYA+xS+zDoBjkk38CIUvhj/
/dc//vPvf84A/XZEP2BhXIhi2D1AtD+QzJhc9LXtfMsMujMXi9X6puvktmrZhuKbtbyWP81t17W/sY/f
TOdmtZYoXPuOfsnMO74cb73Yz+Rc3TubzMUHL/bZ0jylHjXn1rJrmd/te9cAAXqG/gzYf1o615b9YIAD
8n0YzwB1fPUZhiFKjug4Aw+2s+g+OOadAbYp9B67TzitJOhT7QIh7Hj0KbXojSL7+htE9vX3iBxOxpeL
HE7G7xA50t5g5Uh7u5UWDAjNXcs2XQOEMCCFMpgcaIhZS9MxwBaTA1t5mEyolkz8ZMLicouf/6pzC7z3
TWt1s67456S9yEv3KOYTJk+OQcWwX9YHxmIHYwLTalnBhGXdoJ51jHHkUXou08AoX/G94wHS1KKFBMUw
+7uoWf1CL/9ljp8vSPS5efX1xrHv1wsDnNLw588o8vbw+Pn4iOL8337/s977W7L/VBQAfjv7wgtpcon/
4uIk06yVSEbf26PgUxlP9EBnoDRa46zeX8R6vldwrjxICI4u40e3nNV2WEjw4himrbnrufPBxyAIQIy7
KUygR5hnwUj7qUmePmClv5BIc5fKtZ3F0ikO7aOmaVUTmgG2Sut6bY3TOFNoBq5Xlrt0DOCFycH7GSfe
DpGXP060TyWjPFpkTkLHHeShmNMXLUfeEeEfXcbfAFpvwlnWI4iEsEqcXPk+5Up7/wMTtMWhL4Wx3hfP
hfGqQ46xSBai+FGWqPM5wdjT3kIL3dxZml+LSueFYUP9mz0hnxyMEXVKTSJFJQV80TSNFg0YnxQpryty
Xr8k6bNobgg5JT4Q47BQckifOmCoInXAToDa0TvgCPJGBvRhB3ltfltZ3w3w4QqfUgRTsIZPH34p/5v9
GeEYHxNvBz9UPAl8JnWe5XoNJAoGKBUwU+SFv2xgigJJjApxZiQ/cF6y+R5ES7m3hWHzQi9CvuJwp/Wz
nbY/Wlb+6odLcFI/XMpYSNgYp5EXSmc6beqpzBCSl/+yPglWbsuaK60nB0ywyj35QoN73tfuLnMPhdii
K/SRoCMVkmnZjAe1ulVlveZpzoAmtlXtZrb4ipt7KA6wy5JF5VKhOYy97KU1Okcnra4SQ/4qMU2eFdeJ
oaodKKSpoUZuSuk98a7HwNPjUZlxdKF3ag9T9PsCopTFbJjzir2/t+ZCfPwUK/jMRHcOG/oZ1w4kR/aL
e2duWCamvWkLtVIcPyJFynvUrFBdX5DB8vv9icvxfPLltBIXXUfA1qJCaIf5sNr5g2AQ8E4ugXpT5PUi
nMLWRmXEslVpdrkXwN9gKmC/Ka+yeVYZHx53PMEX+mQEXkrQLoRFQnDnx4BHSVAEVl3IDkcRjEkzj5JA
5qEgQfevMUGLRi4BhP6xWQ+23KxFYWyF+YrS1OfAz2h05hJU+ivx8issJVutF8u1W0xvZFBU+biMq8Vq
c2eZ36thVEkT4DT63ac8hbSywtbGa8VcRaODtEq9Eqa/Vh0EvwzGNfwxEO+BU8lVbyjgSpyrjPELi+fr
jL0TOeCUD7qxlr2cgUM5pmgBkHwbQfkwdMkv3hz7L9W5iREhRPFAQMByunsb9EMcP8jBmlOYdaMEKkRg
xMYVryRMQSljolcUJWegjML6GrKjRfW18VYhvK9lLwNo9cueCBCHksOoptnZZeoqsHadWHCuruv6YMBi
hJ9Xn2IfpiGS68Qp3hGEY/4MB9rrQVbuy6/HTW4vycxzVEkGis2GcZdItbkz1w11Q9pbHkcKfb4zcCEz
YsFaNo3ajf+SyqRocu8vPHI7kStdrWn+P4pSa6FeKFymvSB7lRVandWV9mVLawH2pQtL1fIJjPjj7cvH
i9wWbWc8Ho+/fJHOd1RrPP2xqkdzoljBUdSMC0ZAIs+709b3SFNxl8FRq0hgmz7riEWhGkRdyKsMr9r5
0L5Tr8N9XVGI9UZkUpzwUAlNzh1LoYJYtsbjsUhWDX75YGoOPT8f3LRykw9DKfUqnKQLQmTtE3wkwo19
0iK1EjZxKGydjrK3TqKqv1VW5LsUbaVAniKz95dpaqz6F4w89aRgGauCpd8IXQUx1xtIFOPw/P6jnGoU
P9+MaqOQM5vY7zsjJcDghypsUK5gVSIM+siXZ+XwvMZFbb61vFmuWzQ+6Z61Wt/duw1zzlrctutNd/hI
2kyc6wODNq0mWzWdJY32zZVjW9bcdLrX5tWyy4152diCv8pUxLerm1srk1ju2Ok7fbvlAaJ3Irj6wVXm
sLk1F/ZDbXtFMFiIAuAWbuGQpzAdh+fg7bzthF93HfPqa2XSMBgGGr++MJ2vkhqFkArL02T5XwAAAP//
HOJD4rEhAAA=
`,
	},

	"/Template/skin23.css": {
		name:    "skin23.css",
		local:   "oldweb/Template/skin23.css",
		size:    5167,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/9RYXW7jthZ+5yoOxhjgXiD2SI7tTKinmZsEc98HKPoU0BJls6FEVaISu4JW0Mfuozvo
btp9FPyRREpypin6UhOx4iPynPOdf2nFxYHlRS1Rg/aiTGiJISxOUAnOElh80p8Ifff/u69fMNzuilOE
WqRO7WspRf76sT2Jnw6lqPNkGQsuSgxwKOk5QqnI5TIlGeNn/MevP//+2y8RaFrFfqIYwnVxioCznC6P
lB2OEkO4NaL3IjlfwVFmHBqHP15cB2pFCADAClvcbNUyNFdkVkF1pJxDwg/OXS1cy9a0jJQHlmOwTF11
wm3wPipIkrD8gAMwGyQ9ySXh7JDjmOaSlggAtajmK7LndQYNZ5VcVvLM6VKeC4pzkdMoYVXByRmzXAmI
nP2cNSkXRGJOUxm9sEQecbhVdphIiowTllIUOAwGR6RpGlkHLRUXvJ2/V2pUo5sWX8808ux9f3//v/u7
qDPILihOLVrkJElLktGmg6UwtigVZdYgY1ArDEgtRdTRtHKW5PhiY5yOVgU5UE7OopaN5xtzQlF6bxQn
cP7MTWM8uNncdpSxkJEDtclduOGdWgi1iOBnVjFJkysgmMSSPVP1H2f5EzQAQwAChsWnILwPNw77hMai
JJKJHDDoAFD4CD6KZ1pC44Xv3e02CNcXDpuz6pb+so7cCylFhlUuJkJKmnQqKCl7LuKnH2shqRVkjKAC
EjAwSTiLtTqLIyWJVgfNpcZrqeQGjTV/RzJ+X1uqY9y65P/5wDJyoNWH6onl5nt9/UE8Sran8jFcHVj6
XwgggFwsS1pQIrvIW4e3xQlsemgHo7YHUBUkd5PI1e5j4GeSVs/y2YQ3xSlykKu9xi3WK4OMxRd9DR/N
9SuTnDbINduu42VtRkpGeOTVk3Xw3mx5MYS94IkvUKHKCMthBo8pj33Y61ppgGw3gQ9EBbsneRe8j0b1
8kWUyfKlJAXel5Q8LdXvSIX+IhVC0rKJOSUl3gt5dAvP9VA+4kCtaQWZFi4/ulTsZTSvwRXRZ7bNXA3f
eMtJ7vAmLE6+RN0y5sG4NXGaLD2brmaiXrFj6CXp4uHzp23QI8XbUfWxuu3Cad0xXW5qkWGbGwt+R+q4
vSWJ1iaJpgnk47v+t+K7fg0f6PRRAGtuAQ7duCvEbhsZdHCU6rMLtpfwKjmxyDKay6oZlc7xBOFsBdKM
TdKiVSEqaerJazeBXLk/dCfyKbZhNX4daBFCCXu+qiinsbzSY+BY5dnsadWxle4m2pbOmFeIiqn+hEGK
AnSN8jcY32Aw1+U5QjM29Fox/FBXkqVn3Zl6wY+mFP1t+UOYIIBuyNzd2HlDiVEG1Oy9YmDiQo0kCZHU
OMemysdArXGxnUS6GwXrjyoKOmlSu0uJ7AqyOz64HQTeuX333TQUN158WvFgMk3PU5245i0ptnklxfya
qSgDsK/0JJtJ1xmFWutoBc6Q5VG7ecsj2tHLLVt/ce7y2Lx5BDN8nMEz+sYo1nGzUB+EGJlFjQGXj08D
zNhNmZlJmiW0ir3wsQfmU8wCkiXJKzWfY6iLgpYxqWifAxUtaEmk0Gb5JzKtK6b9vBL2c7oVSXNZnlVt
Vohm8m89miqtnSDsmJCBhfbsFYwpzgA/vqNr55Rsws6z7cPDbhcEb848BTETJWV5KjS/Nxa/7uxQK1yV
1mROpfW3Ver70IxKoz1W6PTZfvHwWa1o+sDQvSII3FzQHy8mgklMOP04dIPEqvJIank0wdlz6QLLXifa
jDjEIpcdqDewWKj8HRnEAWnH4AHjjDtGyC64vdNKT7T2LUj/PLu53s7pk7DnUWR8oxDMxMVla0zE6cFh
pbS/0hhISYnpy9M3Q69YpEVo4GT11zgBw3WgJKshDnkSxjs0yRRTUKWiP7UoKSeSJiq/q7kZENwh0Hkp
AYN/epfBMAWoB8zVkR2OXMlEF1Lje8q5eIlAP623yE4wcpjsLo8LLVrFIqHTN0G3zhsoraG1ttswklu1
vPcY6UatyO1A00ctHWw71cH33sNe+2cAAAD//8guqRcvFAAA
`,
	},

	"/Template/skin24.css": {
		name:    "skin24.css",
		local:   "oldweb/Template/skin24.css",
		size:    4486,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/8RYTY7buBLe8xSFCA28B9iOJP+km1o9JGjk7QM8vFVAS7TFNCVqKLrbHsEnmOXcY24w
t5m5x4B/EiUrnUk2IyNxXCJZX1V99cOsuDiyujkp1KG9kAWVGJLmDK3grIDoP+bJ0P/+++HTRwwPu+ac
oSvSu/YnpUT9+rY9yZ+OUpzqYpkLLiQGOEp6ydBB1Gp5IBXjF/znb7/88fuvGRhZy36mGJK0OWfAWU2X
JWXHUmFItlb1XhSXBZSq4tAF5+MoTvUHTpL/6y2ryJG2b9snVtu/083qS3P8N9RiKWlDicoQAIADFZHt
A33YWFkIrWqhLSnnUPBj8NaATDYakJZVRB5ZjSG2P0PYyTa+yxpSFKw+4hjsAkXPakk4O9Y4p7WiUkvR
FUU1KQ6SVLQrWNtwcsG1qOkVHYSsOmS1LKV1BzkpkXkZp4deNAV4RWjVkCPl5CJOqhsBtju0pIfYnCH4
Y1++sEKVGB62dzc+2Pk1gU0aTYbQFRH8zFqmaLEAgkmu2DPV/+KsfoJOm9yHADBE77b36eZ9cFpBcyGJ
YqIGDNoTxhiCS/FMJXSjAL662e7VryxVl3uhlKiwJmwhlKIFROv1Wp++5yJ/+ukkFHUKrK3qwilgYIpw
lhsYUUlJYWCgAcV9rD9a1S1NXqOV8/5SiQY7r3uRDXfqpAHfvVGOaOlWhyyzoXq33jZnTSgHsm1I3R24
IMoGJ9SXPNw3515imJTEcXMedkcfzXfy2X5/YorTDnmbY/NkaMqK0F4iGeHZKC/S+M4uebGCveBFZs+M
Pmw2j+v3Gn9FWA0zyG056JlqaoM1/d6fOzh/pHcX32WTrH8Rsli+SNLgvaTkaal/G/5GByEUlV3OKZF4
L1SZOQJpx62HcpfH+jN2q47YTaKH0FLtYxRVtD5BqKJPRZdsxnhDgzAbk93dWJ8pj/OmONA2tgHnJ7DN
e0ccg6pMwMfZU/smZJOCADNV0Qs8UxMv+Ho2Wm2o90+5HuX7P4MGesecuIPDWeuqg69QYTEdlAXae8LC
1r+9AXxFUS6qitaq7caMyabNJVgKpJs65IpWjWiVTdnXXgJZhD9MjR5LXCnvXARcwR2n2hUhVLDnRUs5
zdXCzBVTA2YpetXbVqb4Gs/OhDDIJfhyahU7XEwh7jd+ttlqK7KfGnbvXA/Uy7Q55vgR422UdJssiKLW
VTM0m1S2kHVhTNJ7HROvTRnndWi+UYUlEt6ETeHNK0wO1YNlvenxXl3nkKy1XQOUT/SsuptSOCmV1+Ac
CNr3SOo7+Ujom3qYpX+zo4/O+e7mbs/xKbf+djb705ytj0JM/KJb07eKwa3jtJ+ZolVB23wU8bmhIAin
MUhJUrd6zMNwahoqc9LSnrYtbagkSli3jKaAZSNapv2AQYkG7OQ1WmCnXTwefH056pto0s97Tietlbzo
6qZNmsmZdDKmOEeZg+yYNhxhQruAqSQYDqdvTPW5FVvijZz7+LjbxfF3Z4s2sRKSsvogfqTg+L1DfoeQ
UvKDkPpKPoWUmq4croEOTQor8qS3bcbz9YN5RlGPb6Ie9KwkpIFT9pmcVOn450/x1HHf2RTN5IRc1MrC
/q4jIp2ig8lDZlsj3fw12Di9Q95a9pXAelRmmHKXzf7ms1lv5/AU7HkS+/lcT1+J/Ne9caPOtNOVRr8w
NhBJidE/cwGf94i/EA4nOfzGTsCw1pN/Zi6jaKRiuiQYoUBXg2FbJCknihY6h9u5SQnCUSm4wMIQoT5o
MHRnfYdZlexYcq0UOS5M/3/h/5Rz8ZKBeXSJt6OBGgagoWbPzEO5KGh43bDxfwju8Aaic/hMVwmbyu1M
b8i103PSfnSruP4VAAD//7fJn7WGEQAA
`,
	},

	"/Template/skin25.css": {
		name:    "skin25.css",
		local:   "oldweb/Template/skin25.css",
		size:    5070,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/9xYW2/iuBd/bj7F0aBK/78ETIBCafI0qEWz7yOt9gmZxCSeOnbWcQos4ruvfEniXOi0
q33aRDMUxzmX3/mdi/GmlCeE5aX0Lt7dnosYi0CmhMFou92sHzcwy09QcEriELy73397/vE9gKdVfgq9
q355X0rJ2Yfe3qPoNRG8ZHEw2uor9O4OnMnJAWWEngNWkKwoWQh6sSB/4QCechkCJQxPUkySVAYwWxrt
ex6fx5DKjMLFAwBw5EMp6P++kgwluPhavBJm/p8vv/LdkR/3yfRnnvwfRr6+IMJMYgGS56GWFHHKRQCj
x7W6zdqQoc0DbezMny5zaVYzJBLCAvDNV9eD2dK/D3MUx4QlgZ+fvKs3Yig+CJThS0yKnKJzwDjDV+/A
RXbxMpQIwgI/9Bxdc6WpLcWb5ijBFJ15KS8tK1ApuTHEeQOcf+bhkcQyDWDm+w/VUkfjnXf1UPBGCiJx
PAYUoEiSN6z+ooS9wgUAGghBYeg/PM6/GWESn+QkxhEXSBLOIADlpgqmh4KUv2FhQ1kF4Onp6Wm10hv2
lEevf5ZcYrvHWCbPFEMARCJKIr1xlGIUW0laIaIkYYGJsbLDCLexVwtDEbwRbgvfRPI8sLBVS0IHd25X
m1jnJ1ALH2ensr/NT8YnAucYyQ5TTcpN9lxKngU6ljrbYPTy8LJ8WSo8KjiKHLHLgXIkA4oPMnQ9Wazz
U9jHytBh5vv3YSNn9F1/znbm8weRFLeD1gDbo4+LKhIE0bCVGHP/3mw5moU9p3Fow7X9ttn4G+VQhggz
HOi7o8jrMHuuaoVxY7W0shtrWrpX/n2laqGv8MhFPDkKlAd7gdHrRH3XiB44l1hcIoqRCPZcpgPY9Tjl
gKmRqfT6dfa5EVmpVZu99YbPFLidMvIGi0yaZJiV4DpRlwYbugZcpzjMl4P2zpoaMoiaNt+w1eSJ6gwx
lxLHMIp8dTtWpbNWHRi9LJ7Xm8d2AVs7YZ6t++UKTIWsFy2lQHOqXaIrKcv8BKvaERugxRD876OvfNjt
k92eltiEYAj6dPGfcFLgeMBH42JZtWZKClurq5Lvetk0oF9Y6zpuK7XSFfEsw0wWl17SdduusxnQpVtq
rt4054U0Ja1Xhz6MzDElEu9IxNlujyidJuTgolOljcos3S5ctYDG7hfdVNsrtvdeLGtsh2xXtqsXk7dx
gSmO5FiPd31oBvNUvzjVrVZHrvF5kvOCqKYdqOYDVVlwNhj3AjCfk3O7s0LTWp1iCT/LQpLDWadFrXpn
Cuw/tsBhYs1wWD2asVGrUYBq8a1gGB5evWmMJDYsaD1Xj3s42jg8LNXdI1zY51ilX+qAXjxn3Fx8286e
++MmfLETyJfP5X+j6wc+yUvPNks82WbWGFqr1YDXWqxmPbd+VbPae4Oem/VzG4+W4PeGwHcEVzIXdRlr
TUZus2lGSq14y3kHGTWE3H597au7TwODNZE4i3ERtcJqX7mVDtYpKRAr1LwfQJnnWESowDVfC5xjgSQ3
0PwbaVFVWl1hdamtTwJWJ2ZSnFXhVk4NJMu8M/9WU+isEoIaETq8Y+iuOAeJ7hNd+PrLho0teLfb1ao/
bv4qM7SLGReYsAPX8j5dq6q3m0R2jZqjIaOcqN82q25Rg2Z1dvUOv5Paho26w6HTjT2r68BXzH7WV4sb
fo8bTtOeuWSxxuxQKVPL0kpKRTD7OWBPR0bEmawc+5SQkUroDiyOo/Zo1Pg5GJiOfzcoUFmmh1/7k0R9
fn5Y2J8o2hbF5K3Dkl9WhsGh7hYmPYW680+V/WPtBRIYmaZqUZl9EJWr5zWyrA/aVwhgoQ8wAGpTS0l3
izNvgqoezWsjgSmSOFY5XwwNja3+YYFXRQiaKNWBg7qNe+rIO01JklKl1LuRKH9gSvkxBH2ptmBmENlM
gZ3za3tijHiM3XO14cDa+YlHm2ghd1tJ/KRud64cHR7UHbq9qX9AMwdENTfuW4fQ698BAAD//0CRdxTO
EwAA
`,
	},

	"/Template/skin26.css": {
		name:    "skin26.css",
		local:   "oldweb/Template/skin26.css",
		size:    5175,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/9xY3W7bthe/Lp/ioEaBf4HYlfyVlLpL8w+6+wLDrgJaom02FKlJdGJP8BPscu+xN9jb
bO8x8EuiPpw22K4moVV8RJ7zO9+HmnG5Y6I4KFSjNxtZZrTEas8ETO7vb2+ubyEujlBJzrIE0Jsff7j7
8hnDx3VxTNAZ6c2bg1JSfNfuDUkfd6U8iAxP7s2VeI7rSHN8s5VCTbckZ/yE//r91z//+C0BQ6vYLxRD
PC+OCXAm6HRP2W6vMMRLC2Ujs9MV7FXOoUY9QXAo+f8+sJzsaPWhemTC/j9ff5APgh02u9nXYvc+QQAA
qeSyxDBZmcvSQlR5BdWecg4Z3wVvDT4Dz9ByUu6YwBDZnyHieBW9SwqSZUzscBwVR4jAPexiRY9qSjjb
CZxSoWipqeiMJoJk25LktM5YVXBywkIKekZbWeY1shKnpbUKOSiZeBqn24YUgHWGQ7OC7CgnJ3lQtXXh
VMkCr7znYJJ91HdXM8tOU7wuRof2n335zDK1x3C9WHlKH0FPZQ02Cf233W4ROiOCn1jFFM2ugGCSKvZE
9V+ciUeotYEa5wGGyfXqZr78FDDPaCpLopgUgEHbzahO8F4+0RLqjutf3Gz2epUXXoEQ8N31/+9urx3d
2nMjlZI51smQSaVoBpPFYqERbLhMH38+SEUdCGsedeIUMDBFOEsN1MmeksxBDcxl/K1lefA3kb41ZRiX
L8WxU8m43nnPk2xMzR01UPXltFJMcWoyCyKIQMhpSQtKVNIkwro4QmIjxASIDnKnZlUQUW+5JMpGRAhP
Z0sysIHjE10Xx6TlM/lsnvGDfX7RmGrkjRWZK0H9oAwNRUpGeNLJ4Hn0zi55toSN5FlieU7ulsv7xSet
SU6YgBEdMMSrIFX0Dwd+tYy88BZLR/I6epf0KtSzLLPpc0kKvCkpeZzq34nOmMlWSkXLOuWUlHgj1T4J
0nvRpnca6ftFE9tClHRDSkdlTsUBQhFNNXDZbtRvotQXhHgVF8euRFMgxpVxsE0dC3OoB9y8t2HkgO3j
Tmr75PAY54Eb5ovGDfFyPSxW0Bb30PVCljnhvaI/UhVeThVBnmyiDJJkHnf0Wfwn9DHdzCh04E4hzipX
9nx5DltLCyHA1GQPrC6qd0aTVOY5Faqqe/Ww35ODpUDqfnqf0ayQlbL146WXQK7CH6ZBdSmuj9XOh67b
dLP+jBDK2NNVRTlN1ZUZ0PoKjObKWW+bma5iLNu6bGq8hc0s5BynK9RDu2K2Y9v33RI/LWTFdOPDoGQB
pox1F1j3YrDP6anbeZooC2oJfD1Uim1Ppq01aB9stfo26Iyc3Np/hLeNTATgh8n1tZuJNCztMwOnU19s
KOqxKSOK2njoZuNYLwkbRRh48xsdeF6a6ZhG5NgoEjYleBv277fD6F+OJTcY+Xbm8+LqV8zKZkNszD7M
7EUUVHRjKk1plftCj6oeNLNeTJ8DZBCMfB2qn/46RD8IhuXxO6fADp9XD4RwYSK8OPl5bk7Xeyl7dtHj
xeXtwyizhtN2ZormGa3STgyNTYRB9TcKqZKISh8kMByKgpYpqWiTCBUtaEmUtGb5N/LNV/FmEIqbQ4OT
SYUqT7opaJVGsnDem1GdoQwjO9q3LIxrr6BPCQ4U/TemaA/JNvA6xr2/X6+j6NX5p1XMZUmZ2ErD75Ul
0+9tK0YIaU7GIM2/DalpgCOQemuc0MDTjfxbfSfD44f7PmAc7qP5zlydmIgGMREMAnEYJA7KAzmovYtO
z8UHlnsO0PQ4pFIor9QrWEx0AvcMEijp5utWxxF39DS74HaPyozK9siAmsP10h6u+3gy9tSLjG9UgpG4
uGyNgTgzo8w0+iujAykpsd3cWST+LoucEWo5OfxGT8CwiLRk8zEEdUT0lxiSLaega0W7bVJSThTNdIZX
Y+MnhPNn8AEFWg81ToN2GtDn1dme7fZcC0UXkuMnyrl8TsBcugHY0Ue1U+XlueGMZqnMaHigtP7/2Pue
5HpHp2m4Lzid7ypLfSdhFxoe40y8rXUb33QOkue/AwAA//82u4DhNxQAAA==
`,
	},

	"/Template/skin27.css": {
		name:    "skin27.css",
		local:   "oldweb/Template/skin27.css",
		size:    5082,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/9RY3W7bNhS+Lp/ioEKAFrBdSY4dR0IvmmRGdx9g2FVAS7TNhhI1ik7sCX6CXe499gZ7
m+09Bv5IomQ5TYbdzELj+kjkOec7fx81YXxD82InUYXerbhIiYjklubgLZc3i6sbCIo9lJzRNAb07qcf
7+6/RnA9L/YxOiK1eLWTkuevWr3CyeNG8F2eRt5Sf+J6x7mvdny35rkcr3FG2SH6+4/f/vrz9xi0rKS/
kgiCsNjHwGhOxltCN1sZQXCpTVnx9DCCrcwYVMjVc3t7e3v9BWIEAJBwxkUE3kx/jMxVmZVQbgljkLKN
c1cr17q1LMNiQ/MIfPPTNSeY+RdxgdOU5pso8Is9+GC/zMOS7OUYM7rJo4TkkgglRUfk5ThdC5yRKqVl
wfAhynlOjmjNRVYho3EsjMt4J3lcyxhZNyLHWIMKQpMCbwjDB76TVcd4s0JJanO1me0/c/OZpnIbwcJv
JH0lPa+UPbETgJ1gHz7RDG9I+al8pLn5G1594g83PD1MvhWbjwgdEY6eaEklSUeAI5xI+kTU/xjNH6FS
GDXxgwi86+UivFw4ylOScIEl5TlEoKDT3uNoy5+IgKoT/RcX67U1JNPaQTej7q5+uLu5snKd8uMVl5Jn
kUr2lEtJUvCm06myYMV48vjLjktijTDwyQMjEAGVmNFEm+ptCU61qWvKJBERCPJEMLsXOC8/6L9UWfh5
NoK7nbH2czj9qPPKwV/niJLV3i58dSnJaS6/lPsWg7HkRWSDX4tMHoZW+rpgL1aEfqP5ZrKh64+Q87Eg
BcHaUls7oS6U2GRc4PsXqiwsKmWB82rNOJYmwVzjAt07TiCoH9EFEizUM+1+3lf9HTyY73sqGalQDZmv
PzHq57oLFxYUs7hT+6F/YR55NoIVZ2ls9vTuLi+X01vlUYZpDgO+RBDMnAqczoq9xWJ26dfKW1s6muf+
Rdzrbc9cpONngYtoJQh+HKvfsSo0b825JKJKGMEiWnG5jW0W20ibfg1e4qurC3UPadPC4m5iqWTOSL4D
V0XTZGwT0e43uVr3GROmjkYFAxp2xpptAuyUXs9wfX9W7DX4yq5t0GkI3m1wc7340rbt0AlDGwWVkf0O
CG0LPAl8d1QMNJIXimUbLPp10hSJdqT2ZPo/9wSaoOyYdYXR0jbIupG7Q6rV7xgEoXJUl8/sdEzVFAF5
Cc8yksuy6nXC/gR3HgVc9fE4oknBS2l6xks3AY/cH3qWdSV25FU2fHYwdSv9iBBK6dOoJIwkcqS5Wt+B
wfo4qmUTPYA0tG3AxgU3wyQCyQvQXaj7gAmVmkHqe3zojg+o54fTCuDbrpR0fdDDrFH8YJrNv9Y/NCdg
fmXJjVKj4NTbd8rdpIniPymWxITKgmzn4VBrd5PezYlwoXKi1iZ18Co0TCjcGQHv3aH6/pU1B6boNHmr
1VU96gwvlByj50pu6nZXjZOStJ7dk72sTgZLD6mjYxY4rK0jrQlcR1hzObdjvZLIdfZ5M6eDM6TuLHmr
d7O+Ljnv4aJG/fnlpykWauAUzlSSLCVl0kmgIY4G7YFDOyQVBVTHgQh2RUFEgkvSVEFJCiKw5AaW/6LY
6vbakJKgORdYnSSX4qC6tXJpoATDHmu0QOmNDDtvt9ChHUFf4pwJ+nd0Mz0Vm8TrgLtczue+/+biUy5m
XBCar7ne7439r17btgvXpBAPmRR+36RmMA2Y1HvGKnUi3ei/UVd8eiCwR3gd8Dqb7/SnkxP+SU44Ezpw
k8Sa8oB3cmuzs95l1hIT6BHccGCHhOeyduoNW3iqgHuAOE5artv6OBCOnmdnwl5bpWkrBJaI2PPzpabz
J/ak9KmXGd/pBAN5cR6NE3WaO0yU9SPtAxYEm9FsEQlehcgRoXYna7/2EyKY6hcF+pUG6qjoP6JFpp2C
6hXtMk8QhiVJVYWXQ7wQXGLovAaBNkJN0KClAuoMOdnSzZYppehMcfxMGOPPMeiPGgCGx8iW7Z0nDUc0
SXhK3MOdif91762QnR2doZFeq8t9deKtL9UVu1Po9Eil822uxviqc6g7/hMAAP//P7SwL9oTAAA=
`,
	},

	"/Template/skin28.css": {
		name:    "skin28.css",
		local:   "oldweb/Template/skin28.css",
		size:    5196,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/9xYzW7jthZej57iYIwA9wK2R7ITJ0OtbjDXmLu7iwHargxapGxOKFGV6MSu4Cfosu/R
N+jbtO9R8E8iJSeToF1VQsbjY5HnfOd854eac7FjZXWQURu924qa0BrJPSthsl7f393eQ1IdoRGckRSi
d9/979OXzwg+rqpjGp0jtXh7kFKUr1q9xdnDrhaHkqDJWl+p23EVqx3f5aKUsxwXjJ/QH7/+/Ptvv6Sg
ZQ37iSJIFtUxBc5KOttTtttLBMm1NmUryGkKe1lwaCNfT36Tf8y3aQQAkAkuagST2zt1G5mvsWig2VPO
gfCd96vWrVVrWYHrHSsRxOarb01yE1+lFSaElTsUV0f1QHSOJiUmeY0L2hLWVByfUClKeo5yURdtZPab
1QYPPkiROhmneSfyTDGQo2he4R3l+CQOsg1MMyuUxDMGvD/z4xMjco8gieOrEVytIzpHGD2yhklKpoAR
ziR7pOp/nJUP0Cp4nWMBwWR1vU2I9aykRzkjNBM1lkyUgECh1oZjtBePtIY2CMuLi/Vah2bpEBjKzbZC
SlEgRTYipKQEJsvlUmnacpE9/HgQklplBqI8cQoImMScZdqkyZ5iYk3SyjFnuxLpqChdxshJri8lGFPj
JSpZy2dSVMj634lM4BdG6oiUqEClPpExJiTP0xDxyqUXTOi1utMIxovgUPN/fWAF3tHmQ/PASvPv4u6D
2HBcbr/Odyz/t+aG1luKWU0riqXyjHNMU+GyzbnAEilapj6i5U11TEdeM/TS7Oq3mXzWn8nGfH5hktM2
chSI9ZVGQyb6rsU1wzwN0m4RX5lHnoxgKzhJ+4gpFAVmJVywHxnI7m+hkBjDb2/spr0ZgdJVfOV0rPSV
PomazJ5qXKFtTfHDTH3XSTTJhZC0bjNOcY22Qu5dHLX3+iBmsboD3yrzfN9mtJS0Tgf0632tuFzQ8gC+
tq4M2Dzv3eAVguT2aqw5ugwqJK9ympPomqUEQRn+7/36dr12qM0qP10t8Kizfp8E1UG5OL1UzJK76pgO
q5ftCp3Q0gI0L8Ii7p6zUV3Ez5cWGyMS58s883PzhfTKOd5ttvxATYoFmeWQLhXSfy5Mg/LAbTw5a2wB
dg3B71O9pZ7pxgM31RFuArzeUKCzLBNFQUvZtIPkGLZo71HA7bBwnKN5JRppKtOoqrzOH7TYLO+Gvggy
RBUaXxPgqf9FN9hQYvtw65hiumVYoc4RYY/ThnKayake64a+uJjOetlc90odpR7kTONDuoNYqKqSbvon
NMo0XFSJhqm2jUCKClyd8R4wHkFgPmensKGC66he2YOvh0ay/KQTp7N2Ywrrt40m+GSf/Uv2esTucglW
t3YeU2apiGlzgmgbWp+jOcGSGma9jkjJ4kUWXceuOdoI//9715PuYnUH3F/cXOiT585sqYnWRt6gvPzP
Ovk0HpThvT/fvH9bXeoVfqFH2Y7mZ5sVMqT9FAKpm0QDoRtKg77xionUL0CLbrb2Nn7ztApvHVfdbhb8
WoiBZ9SI8/xyG+xBrhtPM0kLQpssiKxdcDntLCBZ47JRZxQEh6qidYYb2vG8oRWtsRTGLX9HOrmCrwt9
N4vGXm7RUtYn1T8UpAtJthhM1tZRkLhNcL+FDu0UhhLvtDP8RVfksdgwMXDuer1axfFbs0JDLERNWZkL
vd8bK6Jb2+exb9ICXzJp8W2TulZ5waTBM1apF+lO/7260/Ghyb400AF3bP6kr4AT8YgT3syQ+CSxpmzw
Qe4tO90ujlj2c2TNYIdMlNKBesMWE5XAA4d4IO141WO8EI4BsmfC7qzSw7pOGyWzh/prfSYb2UPY44AZ
36gEFwfL57wxUqdHkLmyfqox4Jpi06ytR5JXeeQcRf1O1n6NExAsY6VZv2eJAhXDR7z5F1St6JdNasqx
pERleHNpUg06hfduBvoIdUGDrtlH6sg837Pdniul0TPJ8QPlXDyloC/VAMxkI/v5c3AODmfVTBDqn2tN
/O+8F1HaROtwv2mQj+oOXjLk1+pO/S40PkVqvq3UsLkNjrTnPwMAAP//91Y9oEwUAAA=
`,
	},

	"/Template/skin29.css": {
		name:    "skin29.css",
		local:   "oldweb/Template/skin29.css",
		size:    5079,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/8xY3W7jthK+Xj7FYI0FzgFsr2THdiJdnSDH2HO/wEGvAlqibG4oUpXoxK7gJ+hl36Nv
0Ldp36Pgn0T9xNkUvaiEXccjkfPNzDc/9JyJPeXFUaIafdiJMiVlJA+Uw2S7vb/d3ENYnKASjKYxoA//
/9/D1y8R3K2LU4wuSC3eHaUU/LtW73DytC/FkafRZKuv2O24DtSOHzLB5SzDOWXn6I9ff/79t19i0LKK
/kQiCBfFKQZGOZkdCN0fZAThjYayE+l5CgeZM6hRTw8cS/avzzTHe1J9rp4oN/8v7j6Lxx2h3yjfL+d7
mv0boCQFwXJ2ihEAQCKYKCOYrPRlZD7CvILqQBiDlO29pxqrhqplOS73lEcQmK8++nAVfIoLnKaU76PA
LZDkJGeY0T2PEsIlKZUUXdCE4zQrcU7qlFYFw+eIC04uKBNlXiOjZlYat+CjFLGTMZI1Ig+h8RxC8wLv
CcNncZR1B7FZoSQeRvD+mYcvNJWHCDarxuS+kp5VCg9CF4SjZ1pRSdIp4Agnkj4T9Rej/AlqZXMTBIhg
sln+Zxs+eJulJBElllRwiEC5QluDo4N4JiXUnRBeXazXOhOXDrDPoofNfx/uN1auaT7bCSlFHimCp0JK
ksJkuVwqBDsmkqcfj0ISC8K4Q54ZgQioxIwmGurkQHBqoXru0SFUuhz4LMvU1yG5rpHR2jOTonDUciLD
kYWVenZeSRQDdbbbm0wJIAAuZiZfYkfnm01xgtjwQdNBsdYaWRWY1xkTWOr4xz6+MFgVp3jgArtRsClO
cbvR5Iv+DB/N51cqGamR81Wgrxj1Oei7CpcUs7iTiIvgk3nlxQh2gqWx2VO5X9mRY8phxIIIln5ahMoU
g3x1EzjNLZCO2nXwKe5VmRdRprOXEhfRriT4aaa+xypbJpkQkpR1wgguo52Qh9hSUblw6QotTJJA3T0H
d/1r6krcZZRiZE74EXwVTebbzNbmNwx1yR/eKqt9jUvNrnFjLGxdlvz86QHXz1eaRBbYIeyktU4MB/DW
i8GyjUF4GwyrErRlyQ866Kh3i/ZYNXijp3D87NJkkCLKLZ49y16Z+gcbFF6zSLcnbdKRWZMYrWzRc8XZ
byQtDg9Ykz+wGjNxYfrVJBF5Tris6l5B7HdW71XAdT+7L2heiEqa8nHtIeCp/0W3p67EdrHastL2mm7e
XxBCKX2eVoSRRE71yNU3YDRbLmrZXPcU7dk2brNCVFR1sAikKEDXpO4LJlKRG2vO3S4Cro14hQG+HStJ
s7PuT43iR1N6/rL+ljQIwE1u642dP5Qa5U69fSf5DUvUiJJiSUyorJNvA3XHY1XeL+E+Jxa3ihNOm9TB
q9H4jOC3C/jo99aP78s9PV85dfU7kk4vuJZ03TqpJK1xX8lJ1oNO06PbxUMG3izWkbqxrCN0E5pfi79n
PLs+PtkdXIlYNOOpp/ndsx28Mty9hQJZ72yF6HlSjQqvLx/y0rhaRYZKkqekSjqsswvGM9MaJEvMKzXm
R3AsClImuCJN6lSkICWWwrjl78hQV5J1KdY1uZn3rU7CZXlWFV6ZNJK3i97EaR2lNzJTeruFDu0U+hLv
bNB/oivwUGyo2nHudrteB8G7M1aZmIuSUJ4Jvd87i6Zb29YYH9ICj0FavA2p6WYjkHrvWKVepBv99+qO
h4cJe3zXAXdsftBXhxPBgBNeVw99klgoj/goD5adbhdHLPs5QNPbIRFcOqPescVEJXDPIZ6RdlxubRwJ
R8+yV8LuUOnJ15wAUHMuvtHD2wBPSp97zHijEowOdq95Y6BODxxzhX6qbcAlwaafW4+E3+WRC0LtTha/
thPUMUhp1j9VoI6K/itaZMopqFrRLpuUhGFJUpXh1dgs2Wkl3s8b0EaoCRq084M6fM4PdH9gSil6JTl+
IIyJlxj0pRqAGX5kOyK+Pmlc0DwRKfHPhyb+d95PPBqidbjfNNI7dcf+dJDdqDv2u9DwVKb5tlaNf9c5
F17QnwEAAP//VGZ+y9cTAAA=
`,
	},

	"/Template/skin3.css": {
		name:    "skin3.css",
		local:   "oldweb/Template/skin3.css",
		size:    1909,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/8RVzW7bMAy+6ymI5BoHSbMWqHTq2gUbMGBDMWBn2VJsIYpoSHLTzMgT7Lj32Bvsbbb3
GCTbsfODHgYUo08WSfPjx090imJHakh5ts4tVkbQ8fJhuVzeM7InwTkBLyZQ1mSFxidOfZNAYT6bXpee
QXO44huld0Bh9Jlr7pVB+KgM+l0pRxOnNq4yk84zASetWk1Gf35+//3rx4gByVCjBQrjWTRGXGZR65Tb
ZMUzmUQ/hQOu3u0KLnB7CFjMwsMABiGFygut8sKfRg1iFuI44ryQ4HZ9Uuw8yFuerV/wc2svgs0q68JR
ZtG5gisbqJ86JaSEGlp+KIxvozGSohXSUnColYB5+Qzjm2jstWZEtDIyKWRgicL8Kn625EIok1N4Uz5H
xBuujMfyIuYjYDevA2u6kJvA5wv87Mm08VpbXwxc3IcnBnostTJr50I/58T+N/wac6gJPkm70rilwCuP
rJ/GfBbGseE2V4ZCfOkqLK7DK5A94TS01kzqXH3t8FJdydeTlJfPPhEyQ8u9QkMNGnmREbKHaOSOFqHr
GgbV6T+tnENPfUtNz1YKdgoMIiZfWKzyos3dtggjaOgoLLgRDPbkjj4pp7wUpIazrzUpLceRYtgTMi0k
F2EeQ2jNPTssjEaavT66y9WdJM7vtKRglcglg/bQY5lslfAFDVLqg21ceUNP60jRe9x0nqthjpar45TY
HdcqNxQyabxsdlcaFDr4pcDgn0KmGvO08h4NqQ+9BJU3eh/fRWN9er9So7Gh+mgz06OR3gbajoV03ayo
WFuZsvKkJm8/PT68e6RdwR4CI18/PHx5T+H2pt1sGnNSH5WFtm5/Peg8UEUGjAS2ThXd7Mq/AQAA///x
zIwtdQcAAA==
`,
	},

	"/Template/skin30.css": {
		name:    "skin30.css",
		local:   "oldweb/Template/skin30.css",
		size:    5058,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/9RXzY7bthZeh09xEGOAe4GxI/8mI61ukDFy9wEu7mpAi5TFDiWqFD1j1/ATdFX0PfoC
Rd+mXfQtCv5J1M8kmUk3lZB4RInn9zvfOZxxsWdldVDojF7thCRUxipnJUy22/fv3r6HeXWEWnBGEkCv
/vffD58+xnCzqY4JuiC9eXdQSpRftXuH0/u9FIeSxJOtuRIvcRNpia8yUapphgvGT/Efv/z4+28/J2DW
avYDjWG+qI4JcFbSaU7ZPlcxzFfGlJ0gp2vIVcHhjAAAAl1wkPxfb1iB97R+U9+z0v6/jNzPbM+yf8Mk
TVPI2JESSGmpqAQlqsTISgUXMobJylx2LbS0qKHOKedA+D54a2y29um1Ass9K2OI7GOFCWHlvnkOvZqv
o6tE0aOaYs72ZWwNQheUCVmckZU0lTYC+KBE4tc4zZqlvhEXhGYV3lOOT+KgzigM0STLsq6ZVsaYpY+M
qDyGt8u1d62nKbBc24MuCMcPrGaKkmvAMU4Ve6D6L87KezgDQBtmiGGyXK9v/+OUGVmEpkJixUQJMZSi
pMYZHOfigUqXcJ+k7XaziZ7cfCgJlTrURsKOi/T++4NQ1AmxjqgTpxADU5iz1Hw4ySkmTtVXIUsxxakB
VtLZMpW0olhpL9yf+r1P+zKyER2kXi8OURiEfWE3fg6VPo2RxYJ3qa5weQ7Bt4qiq/b15KP5nd/Z30/a
rzPytkTmSlBgykLLD+3489efdB2HKpZRdKVNKDAr4ZxxgZVBSg9vOhzg/8012iz01potkBFAywOcU06x
jHdC5UnHSZPRnnAH3vmq+SJkpcxcyaOQZPoocRXvJMX3U/1scWAU5vMe5tbmCpU3Zo/UCLScYBYfHZXt
BCd2OSCLxkpDrtOdUEoURgPBdU4JTNJI30NftqvtZrsKzV7+s8y2Vh88o3NWu9r0HNAlpwHPBsD5jD+G
FrVspmgBrNg7dR1CXTv+xM2XAaG1aw2ztUvfSHGtoG/lunw+M3R3Z6ipx2TTStRMb4t11wNfLl/irXFL
ngMZ38bXN/ZDn7x5CEaX2ibVC/9iWR3NQxABJXFZ6zYZw6GqqExxPeq/T/QDlYqlmDu6hYIRwkd3BD1s
8MYnfvDCpn80VBdE2MN1TTlN1bUZwc49Qh+lIbPNanlxEu3v9NRtIk22gvYD3x1qxbKTCUij+C4TQg3a
4QtB5CGweeuKTKupRK2MeJd0V4eud80IVtS2ot7oYYPs+1LYcxbvdFvzstsi8GkJKzJsX/A6bKSvnwfx
VuEnelTnwYw3JuuCAgsD0HVWPeA6iyNcE38V0wyZupnbYeIk2PEx0PaNhGRkbYXoRWURXSVDU3zTeBfp
O+nViY2yZklC67STVbcBPZGyz1OGllrTikqsxN8E9obf1r47NQTnFNJSyVPTj4YlsOiyoY+SEeR6RiPC
pEq3o+5K2Lt6bzSERpYt3DqRfQnjOxcLISkrM2HkPZN//N62gEOTFviFJqWiKGip6oFJi+rY+2ZwwJw2
+t/rOxmO5e5kDCGUP5hrtOfNx5rePASJM+UOH1TuoOmlrNsJDppRPLCmJyEVpfJOPUPERFdvGJCRePdM
fyKvzaSlRGXrQq+5MX21XI8pJOyhl/ov1Pno9PGUuwN1pjnPtPXXxgcsKbZ0EOTVsWWb1oEhWmzQOBvK
tY63Im5Xt+vbtZuvzNEGzNkmGEvBtkJP9Z4LNBPZYXWIwTD8EIM/V14Qat1zdpnggz5/eSUXhDqO978J
ZjnQFBXsm0jKsaJEM0s9Ns13ulAwdUMLnMZDaEYApM+ts5ztc661oieK8v+Uc/GY2NOJtmdSYpJJXNAz
YXXF8SnWyi8onNv6Q0WIHg2eC5qlgtDw4GrxehNdNacpY7sDiKl7oZSue3Kj76Rz6lzpOwl74vBIa2Cy
qY4XtJPh68tfAQAA///LpR2zwhMAAA==
`,
	},

	"/Template/skin31.css": {
		name:    "skin31.css",
		local:   "oldweb/Template/skin31.css",
		size:    6126,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/6xYTW7bSBZes07xEMFAAkgyfyRZIpFFHMfI7GZhYGZWQkksSTUmWRyyZEtD6ASznHv0
Dfo23fdo1B9Z/JHjNFpCrLDIqvf3ve+9x2nC9jTLjxxVyNmwIiZFyA80g9Hj4/3y7h68/AQlS2gcAXL+
8beHp+8hrBb5KUIXJDZvjpyzDFUIOTuW8ckOpzQ5h7//8r/ffv1/BHKtpP8lIXh+foogoRmZHAjdH3gI
3kwc5Gzw9nlfsGMWT7YsYUU4Wjy4M9ePkKOuH+UnqjXMWEaEAhsWn8dw4GkCFWpOCUczz3vwvkUIAEAd
AaNv34IgCNSarWpaQnkgSQJxsrfuSqWlznItxcWeZiG46tI2w5u7N1GO45hm+xBc/VXPcXLiE5zQfRZu
ScZJIVbRBY0yHO8KnJIqpmWe4LO06YJ2rEgrpIRNCuUlfOQsMmsJ2dVLlp4zFRE0zfGeJPjMjrxq6a12
iJVXGvNDCEvXNbZ1z+koLkS2ohQei+TjLU3xnpS35TPN1N/AuxXS10r8dE93n9rBLUhOMA/Vz+QcoU8I
XRAOX2hJOYnHgEO85fSFiP8lNHuGSnirDiKEApYKCrWOMdmyAnPKMgjBAAPh8MBeSAFVGwJfVjPfu7JZ
7jVhDIwfbFTZshUSJxvGOUtDkSUx45zEMAqCQAQ4JdkR3rCtb9qb2tWmmYOlfVU/Q7q5ZE51OkfqJHKM
xa5KRSvBLghtErZ9/s+RcQKVTnCVzO50RdI6P23POBpx0oOOjdq5LcJkuv/VnbnzZrnk54SEMS4PJG5W
FWZlMjqtEJkrJcFzr/DJ3HdnbiCRMToQHEtk7GjCSRFCQV4ITp4KnJUf5V8q/PN5PoaHo/LVZz/4JBPa
ygqZnGLNgMuVH7HS54+3+MZYwFke6pQ0S4oA9OJ78k/ZJlMPMqYTTmw2VLWa5yeIlDs1A1yMSzjlCans
e336imCXMMwVJ7RUX4gN9Vkw+i5/vbX6fZJnI+OrGi+Nq3xBPbafcEFxErWI1ndv1COvamHDkjjqQPCC
EBodS1KsabZjgBynQo7Tsthx+nYhx7EsQ04X2Y5jG+trY1NMM6isjU0ZyE/2P+3yhVSgw7ctExfuTWS8
NJef6JUV8eS1wHm4KQh+nojrqAuH6fR2Oh3EhNBxvdlLUAi+He0Y46SotgnBRbhh/BD13dGBsCVtImVc
h6A43Yhr7cuZSqwaSf3K0EC2BuxdoDytlF4LTSvUioWng9o3QmS7ZEvbVtQPJNLw8K2SKEOqc9zRytDs
QArKIzQYEfSeBBXq1MG4KKDmdKtRarOl5rK3miOnyQv1rDKjvhzyiJEINN1Dz5PS19ppB09Xz/fY9d0z
Vtm847wR/tqr8zuprTbOLoJWvfHbzYqd/+32rFUUrAgPZHxjadDqE0ZfvfvV8kudyyID6lye17nsue5N
T8+mgXqHngbkvpefENS1/ZhodRJacl0QoV2tFUQCt9ed5ifwhbreXOs6rGDX2xc02rI0JRkvq07qdztd
61HAVdfKC5rmrOSK7nsusO8CHtsXsidqr+jWqdK6rh6X/mxpM9MyPwm2j+nLuCQJ2fKxHGW6Fgxm60Vs
m8r+Rnp7CKnAWQ6qHsAAW0HTyEJv0Gk3C/DvY8np7ixBVwteK1L70/KHKjws7vQoIMQId8rjW7iBwDXj
Qow5UcHSXl664tstUb1I2qjwlwIVRpzsIqRMU8Z04HqDF3ywW6EP78wlUMkkZx0jrmrz5A8qlNi2lvvM
jOK8VYrat+vgmD5BOyEQM3HLywubhft9tyF7PUGotOww19//KaXbo8akk7nd24ou1MTeu2m10U3AnkRJ
7fUgHQDU1PhVDtEXy/n2kNNaNfNOa9GMdTbfGlvaQYXhGe76pPOeAao/312d4wxsta2PjHXcJLrR69v7
ieRbflyt3JnrahainKQxKbetrNH7h6lF28fFtLJjRRrCMc9JscUlqXO/JDkpMGfKgX8FxdhVRvzzTHNr
RJKMF2dRtYRFA7zjd+Yb7TbwzCG4OUJiYAzdFWug7t6RFaS/rGDY8u3j42Lhuj9NOMLElBVEDhbVz5O+
2dtQpK2Sj4dU8n+sUl2OB1TqPNPr6Ca1/Hvxjfqjq34jIANusP0gPzYkvD4m6jBb8bVUWeMjP2hwmlPm
TZMFnUHJHzhhyzJujPqJI0YinTsOsYyU3GnbOBCOjmVXwm60kmwuWzKxpt+/zYL5kD4xfekg4wdEMICL
697oiZMN01RoP5Y24IJg1Y9oj3jv8sgFoeYkrb+0E0SzIV8liP4WtUR0H5FLilxBcEWzbVSQBHMSiwwv
h/rj+v1Y0wxLyoEmQnXQIKxdUeY4mx7o/pAIoehKcvyLJAl7jUB+RDlQzRtvetzrjdIFTbcsJvYrAhX/
lfXOWKqoHW6XkHglvpH9CnI3E9/IrknWbNt6HyOa401rzL/8EQAA//+s380c7hcAAA==
`,
	},

	"/Template/skin4.css": {
		name:    "skin4.css",
		local:   "oldweb/Template/skin4.css",
		size:    1644,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/8yUT47TMBSH9z6FlW6bUcowlWqvhnYskJBAIyTWjv8kVl2/yHZKS9QTsOQe3IDbwD1Q
kraTULGBGTTevpf3ffHvybfEGrfGqMEaXEw13xi7J8l7bnk0DvBb4yDuK5VMg9mE2k1PlSkOyhs9TX5+
+/Lj+9eEon5CMJ8VmWVXN1WkCEe1i6lUAjyPBhxx4BTFAix4kkwYm88ZSw4I3ZKtCSYq+QxMuIhmq56B
SAlb5f+3R+0DeFJyJx+khMiyxaKVykHuUYNyLtaFh9rJ9Cy+urtmq4SiIDxYm3Ofai7UsY6Zbs+wWpqi
tKYo46kFM6Y1Y8Oeaznq0FoIrfGwQ3K/DiWX8OnPpFGddTOGZe794Gu2XI4doudi/fvwy/vsGybLZZsf
RQeErqKJVqEGPW5+L7r0LnBXG27co8NOy3LE9dvZ4XILRXhqXtad/jYtFHkdI7Q/mYOXyhM8q3Y4gDUS
T3SmsnxGLzYTT4SYz8+Z/YPowBMvqkixNU6lpWo3lOA+l6OocVUdUYNevbtf3d2fHR58Kfr4ZvXhNcGL
rNo9udpNyzh0ZqgZwfBfJTbaxh1F3VPCrSkcsUpHisb4lz0e/woAAP//FBPatWwGAAA=
`,
	},

	"/Template/skin5.css": {
		name:    "skin5.css",
		local:   "oldweb/Template/skin5.css",
		size:    3039,
		modtime: 1761792052,
		compressed: `
H4sIAAAAAAAC/7RWXY7zJhR9jleBvk+flGljy/bE+bFfupMRNsRBg8ECkvG0mhX0sfvoDrqbdh8VGPw3
JBoprR8iB3O4h3Mu95ILzhX4LVidOFOhJL/iHCRx/KMIVmE4jIWdzEFFYdOu42ifCdxsQBztDgI34GcQ
R+n1TQ8czKenBVY2I/YwgAfss8YmHlwJJXbIxKKO2QDLDC5KUl9MWg/IKO1DJlHisLse6gN2dATuHXDb
AxMNSx3sIwhKjt61dg0UNWE5iAur4wk2hL7nQJJGXtjm2z9//v73X39820jIZCixIKdipvgVivVy65oZ
JQyHZ0zqs8pBEu2KYFXC6rUW/MJQWHHKRQ6+n8xTBCs3EJvHUCRN3TPswjeC1Hlw160KL4rrZblAWJgt
fARBROE7v5i8mKP6aToyha2xx75NYS8vDSRsM/6VBGG91hULRSpIQ0hJzXKgePsZpye2ECHC6gWdcSFL
Kt3GbefXBMc4LpMpOgzlK2HZzC+7ezOJ1+VFKW7iOzWStgOSU4LA95Nd8K4B98y/73gnPX5vB2qEtb0d
95hZVY5GFAscjvYDrBTulLOM4pO6SVQRRY0/TpjjsU/EByjQ2i/MLEc8FDUfBpv/mk5HPXTSKZ3nPif9
jBCWlSCtIn2eLbP1AWKy8RDLpsSSz8SEntgz00dL8faxfHF1y4y8WRolp6jwmGBrScmV4s0so139mnGt
MFNYTDe0aztXIEqb6u5kJ/pbujUbfnw7C1UPo2LLmP9TuFvZBBVWpMFnDBEWiy7uT5CvsLth3KSrDJFP
nKtJ5Acy1xMF5pSw100A8yuRRGGkX2GlyNV/qo1ICFdcQH3AcsA4w3alM7/2PJdx7qB+aTAiEMhKYMwA
ZAisG8KGPprGcds96TU/d5hZwzUTi2D1EQSrIVNt2oTazRzYRuYGRW/A1uFukBljHEcuruhNJa8grdae
UgZ+0jexTOs/Hqt0wnZRr76SvZOCk7adOxVmtWUbdx3rOfvxtW3ud4e55JvhDSixmYTobyCekIjIlsL3
HJSUV6/FSMLecPxErS+Kt4M+nouAqEu4TtPtBpifZL83d9anG97nIMlGcRax+r426XJm8sycScn29Wit
578BAAD//297KlTfCwAA
`,
	},

	"/Template/skin6.css": {
		name:    "skin6.css",
		local:   "oldweb/Template/skin6.css",
		size:    8058,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/+xZ227ixhu//vspRov+UivFLIYEBXNFAmGtJTglXu3hphrsMbEYZpA9bEmjPEEv+x59
g75N+x6VZ2zw2GPjpKS7XXVWWkXOzHf4fecvA/Cg/e/Knjr6+5E1fuOYgNBwBXEf8I+31qeRCaIVxLgP
Lu2JPTNBo9Ppdnu95MbV4NqafDT//O2XP37/tQ+c0QdHH44u7dnAsexpTI4g7VG7mNiXb394ZzujmOHN
YDi0pmN9Jlierbd9kH6bjK7ST0URLgaXb8cz+910aIKG343/7V9e2I5jXydvU2G7/OwvOfYNvxHLZA8/
xtJcD2Zjayp+0zrMdxPi75rN19YKLlD0OloGRPzffU3g5x/ni+Yi8L8HDZ+fPkioC7VaKtGSGwkYewkk
aLVH7WbGwbuwZ8PRLL3e6PEDjPUWRBQH3l7VLLrJI65jxZNK8PM4dzKExUMF5b3TxKcPJtZ0pL9JfM2Q
LM+Fa2eIpowUZPcG0VMOiB/tUWvOMXWXLGAYKZytXXQ26VPKlH8UpuGICMMoZC1KIhwzkWShkMFQeLwC
C0P4Kacyp969wvoiFiusb7QUrPY+djjq5ZBLnDoPlqAo+0JRtEO2l6jsjJ/Q6ay3wKObOUZyeIBdfDRd
ulohwiL9P7CqwTp5dQMxZAGhYBIQyu7X6NXJZxR6kMATAMMA4hMQQRLpEQoDn/vghjFKiqCWg9nK553S
fPMUhPNgFrFUJh9RsSQAVfhl3qbQt9siCF2IEfFg+IyCKRK9RKRYd+cUe1VEfL/Xa7WyRO4Q9J4gjdI3
87VI9rrTRHURV4aQOh8zipDJ1Y/zNVNEQbYU5kMl9Rel96pzLoenvAFJlWh/JUo8MQSVOvd6sVvHynmQ
PaXWPTPWjNbBzqpmVtIetcYKkc2/TOamj+HCWy5ChMg35EetVrcrUkusH2bfnn5p6lxBNwq8FwiVWoVf
1VKqR4JCGlZ1niVdUBxXDG3ZrjRIgkrjiPB8BbMq0mlfXat6KdiV0KYhJAtOuFjx1neU0Uzv4dg3+ntr
6Lwp1n/Vd4G/9JuMFXbXuCdkbnHONGLI+xtDMq9Hg4k1npoAI59JfWpM/ci01/QnFAqJVR4uzYEuP9mm
JzsKq5rhYkgUDC8/k1x/H4+xBjW9PJ+Xi0JnYXARYSiMgfia4rydBDo4PTt2tMdqtr8WPY0XSWgR3YQu
erl6pG4KCgIdoRDtVxQRC4M1qtxRSKF6ftrr9PzyEep5ttWt68F4VLXSEnLylVYN+58fhFUZ0kXlJiPH
Gc3025vBpTUdm6DVbKNVxa6lNAncEy9wK5rjIyS8nrwF2pm5BK9akaDWRl16686fdQt9Cfp7AQZfUoRd
7Xzi9Ht8LELoLufQXe62TV9wmXRAu9b/FSOPrETdVmSr118nyBw2IVbs5DLl3IPRHSpbypU1LvlH/+TS
TiHGcwxR2eMIwvG8PIeEoLB0m5zb8Luu70trQNW2+RBA7W4ht+VXaTt8zg6PeGfq3X5B1LKYSyGolYAq
ZJelzBI27+hnFL4Q+XXgsiimnZSWU5Eg7FtLbKrgPKJ4w1AfiEIgYrQxp1seNyovTYtv3He1z1tpq5k+
dSlhiPC4/qRb0+Hogwk6JQ6fJWWcZal4KHLDYM0Csf99XoaQZhZnNpjeXtmza7Ge20MmnCFmigOyjCTB
jT6QNssqJZLhjctfAa3ROSutsg1cZN0uYZdZXx+D8wq66VIs0fS0XNXy2Tb5+ZB/dRPzHpGlcV6LpdbE
dCH+oKA9aHMaeijM7N5BY8BPPy4bi5BuiKe7FNPQBI0rfvqaTwnTfbgK8P3ub8/8WxT8jExg8C4KBwTp
dyhY3LEk+6TMA7LeMO1BExqZKcdMC6olKnGN4kKG6UJ7kPimPYK2Z8z5agxtmQ5xsCBmPJb3NVmQU07x
rwAAAP//1x4Y9HofAAA=
`,
	},

	"/Template/skin7.css": {
		name:    "skin7.css",
		local:   "oldweb/Template/skin7.css",
		size:    1482,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/6yUUW7aQBCG3/cUI3jFllEblKyfCJAEicYRspS+ru3BrLLesdZjBEWcoI+9R2/Q27T3
qEyK2iKaEsX7ut/8fIN3JqFsA9tCuVxbCcFO+ImhHLYLsuwtVKHNRkKli6q2vc6Pr5+/f/vSCWF/W+lP
KKEf+Bclh5CSISeh+25/dsKvCmVMAx6FdR6UUawtwUxb4k2Jnd5LP3BV8k74qTKlw5WmunpjXj8o1zvh
F2R5aVWBbelZXHM7apnanBA7KuzBCl2mrDq2CePJx9gbzqa39xKczpe8j2S0dZGga6VdVrnRFqtWwhLl
WLPBVzy6ps2b6D72HifT27tYQkIm+6vxFC2ja1Rbjza4aLS1ZUevGZRBuT5TeiiNtk/bUTSL5vuRGgzS
NATGNXsZpuQUa7ISLFls6JWuNGN2foFKWa/wfH5JK3QHPDE1/pP1DeXaljWLrbiO5uPJ3Js/d9u9DC6D
xQL65RoqMjoLD0AcPbx0PZvcnC5/nI7jOwlXzR97gK+jOI4+nMDFs1tSM5MVW5GQy9DJ3wB0h/sTikSl
T7mj2mber60G3dFo/H4ShOLPz/2/ZwTNjHhLbGZQQv+i0dyJePzmLXFy4/4MAAD//74cazHKBQAA
`,
	},

	"/Template/skin8.css": {
		name:    "skin8.css",
		local:   "oldweb/Template/skin8.css",
		size:    1262,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/6STT67TMBDG1/gUo3bbRA2CJ569QmIBEgsWSKydeNpYz/FEzvQfVU/AkntwA24D90Bx
GkjSIr3XN8vYM9/3/TxJHa2trzcsjiKnYDBIyOo9NOSsgfnbWEp8+fDu83sJb5b1XomTaLvyDTP56213
sZTIdfGwDrTxJinIUZAA8/tYSqzIc7LSlXUHOfuknWbrCT5aT3yocbZobNVs/GL2+8e3Xz+/zxTEhsZ+
RQn3NStw1mNSol2XLCF73TkTOZnDAtgsoIYjgPjbBRKyrO0bKcNjpLuOXZQCCZ5CpV0/qOGDw+FXxj0n
BgsKmi156cmjEicAEGlOIbS0htR4Su0k0qbSzl36fxn9j4OnS6wUtNNPQqSNNchUw3Gc8gkxO8LZq5qV
OD/afBlLnU0nOTFTleys4TImmJ5EJrLLNT3rZ/ZpIy7t7NpLKNAzho6ANXi8MPDUpRlEivAm7O7aT/8x
YDQj2wpL1AZDD3RA5zYvu7N2Ts5cAh7oroj4n+5tmbuNuaKipbP+YRRqfLX/S6fLDOdtFlpubWMZzfOG
6ILtFh8xo71c0nbyEuO7o5W6ovfiTwAAAP//r+4W0e4EAAA=
`,
	},

	"/Template/skin9.css": {
		name:    "skin9.css",
		local:   "oldweb/Template/skin9.css",
		size:    1148,
		modtime: 1761644483,
		compressed: `
H4sIAAAAAAAC/7ySQWobMRSG9zqFsBfdeIyntqkjrWrskkChIRS6lqw3Y9Wy3iC9cewMPkGXvUdv0Nu0
9ygaJ3XctNSkUAZmIfTpffzv7zssdU2EnjVMYzAQBM+rLY/orOHdYgADnUutFqsyYO1NtkCHQfDuZHox
mw8lK9BTVqi1dTvRuVZOkfXI31qPtKug04t2HWvf63z/8unb188dyVsg2jsQ/KIiyZ31kC3BlksSPB9X
W8n2jCUx66uaWMOm725m85ufM49+kn24mr2/FHwyOGCJYs2JEz9Hih2l8kF/XJFkBFvKlLOlFw4KkuzU
c/TgSUr/x4mH9Luv7sNPAjNFcAnKQPhXj9EZFpNk0TK390canZH8N2asf42R3iBSq/bo4ZDI9o5Gs+PN
Kbtnr4WzfvVwPJ2nT7a8gQUGRRa98OhBLuoQMYil8iZhGxstgXkGqRZkN/AMcIkbCH/ham8gpBxPYca6
a+BNhdG215SO6GoCyVPyYjzMJWElRuNc8rvsyhvYipd71tUOyz9j+eiA5cPxEctTUxIXfy2JCla53nld
ebTCj3UkW+xePKnk017fYjCZDqBWov1nyrm0/B8BAAD//8Xvs9N8BAAA
`,
	},

	"/Template": {
		name:  "Template",
		local: `oldweb/Template`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"oldweb/Template": {
		_escData["/Template/skin1.css"],
		_escData["/Template/skin10.css"],
		_escData["/Template/skin11.css"],
		_escData["/Template/skin12.css"],
		_escData["/Template/skin13.css"],
		_escData["/Template/skin14.css"],
		_escData["/Template/skin15.css"],
		_escData["/Template/skin16.css"],
		_escData["/Template/skin17.css"],
		_escData["/Template/skin18.css"],
		_escData["/Template/skin19.css"],
		_escData["/Template/skin2.css"],
		_escData["/Template/skin20.css"],
		_escData["/Template/skin21.css"],
		_escData["/Template/skin22.css"],
		_escData["/Template/skin23.css"],
		_escData["/Template/skin24.css"],
		_escData["/Template/skin25.css"],
		_escData["/Template/skin26.css"],
		_escData["/Template/skin27.css"],
		_escData["/Template/skin28.css"],
		_escData["/Template/skin29.css"],
		_escData["/Template/skin3.css"],
		_escData["/Template/skin30.css"],
		_escData["/Template/skin31.css"],
		_escData["/Template/skin4.css"],
		_escData["/Template/skin5.css"],
		_escData["/Template/skin6.css"],
		_escData["/Template/skin7.css"],
		_escData["/Template/skin8.css"],
		_escData["/Template/skin9.css"],
	},
}
