// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Bloggerfriend is an object representing the database table.
type Bloggerfriend struct {
	Blogger int  `boil:"blogger" json:"blogger" toml:"blogger" yaml:"blogger"`
	Friend  int  `boil:"friend" json:"friend" toml:"friend" yaml:"friend"`
	Reveal  int8 `boil:"reveal" json:"reveal" toml:"reveal" yaml:"reveal"`

	R *bloggerfriendR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L bloggerfriendL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BloggerfriendColumns = struct {
	Blogger string
	Friend  string
	Reveal  string
}{
	Blogger: "blogger",
	Friend:  "friend",
	Reveal:  "reveal",
}

// bloggerfriendR is where relationships are stored.
type bloggerfriendR struct {
}

// bloggerfriendL is where Load methods for each relationship are stored.
type bloggerfriendL struct{}

var (
	bloggerfriendColumns               = []string{"blogger", "friend", "reveal"}
	bloggerfriendColumnsWithoutDefault = []string{"blogger", "friend"}
	bloggerfriendColumnsWithDefault    = []string{"reveal"}
	bloggerfriendPrimaryKeyColumns     = []string{"blogger", "friend"}
)

type (
	// BloggerfriendSlice is an alias for a slice of pointers to Bloggerfriend.
	// This should generally be used opposed to []Bloggerfriend.
	BloggerfriendSlice []*Bloggerfriend
	// BloggerfriendHook is the signature for custom Bloggerfriend hook methods
	BloggerfriendHook func(boil.Executor, *Bloggerfriend) error

	bloggerfriendQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	bloggerfriendType                 = reflect.TypeOf(&Bloggerfriend{})
	bloggerfriendMapping              = queries.MakeStructMapping(bloggerfriendType)
	bloggerfriendPrimaryKeyMapping, _ = queries.BindMapping(bloggerfriendType, bloggerfriendMapping, bloggerfriendPrimaryKeyColumns)
	bloggerfriendInsertCacheMut       sync.RWMutex
	bloggerfriendInsertCache          = make(map[string]insertCache)
	bloggerfriendUpdateCacheMut       sync.RWMutex
	bloggerfriendUpdateCache          = make(map[string]updateCache)
	bloggerfriendUpsertCacheMut       sync.RWMutex
	bloggerfriendUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var bloggerfriendBeforeInsertHooks []BloggerfriendHook
var bloggerfriendBeforeUpdateHooks []BloggerfriendHook
var bloggerfriendBeforeDeleteHooks []BloggerfriendHook
var bloggerfriendBeforeUpsertHooks []BloggerfriendHook

var bloggerfriendAfterInsertHooks []BloggerfriendHook
var bloggerfriendAfterSelectHooks []BloggerfriendHook
var bloggerfriendAfterUpdateHooks []BloggerfriendHook
var bloggerfriendAfterDeleteHooks []BloggerfriendHook
var bloggerfriendAfterUpsertHooks []BloggerfriendHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Bloggerfriend) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range bloggerfriendBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Bloggerfriend) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range bloggerfriendBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Bloggerfriend) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range bloggerfriendBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Bloggerfriend) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range bloggerfriendBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Bloggerfriend) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range bloggerfriendAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Bloggerfriend) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range bloggerfriendAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Bloggerfriend) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range bloggerfriendAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Bloggerfriend) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range bloggerfriendAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Bloggerfriend) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range bloggerfriendAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBloggerfriendHook registers your hook function for all future operations.
func AddBloggerfriendHook(hookPoint boil.HookPoint, bloggerfriendHook BloggerfriendHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		bloggerfriendBeforeInsertHooks = append(bloggerfriendBeforeInsertHooks, bloggerfriendHook)
	case boil.BeforeUpdateHook:
		bloggerfriendBeforeUpdateHooks = append(bloggerfriendBeforeUpdateHooks, bloggerfriendHook)
	case boil.BeforeDeleteHook:
		bloggerfriendBeforeDeleteHooks = append(bloggerfriendBeforeDeleteHooks, bloggerfriendHook)
	case boil.BeforeUpsertHook:
		bloggerfriendBeforeUpsertHooks = append(bloggerfriendBeforeUpsertHooks, bloggerfriendHook)
	case boil.AfterInsertHook:
		bloggerfriendAfterInsertHooks = append(bloggerfriendAfterInsertHooks, bloggerfriendHook)
	case boil.AfterSelectHook:
		bloggerfriendAfterSelectHooks = append(bloggerfriendAfterSelectHooks, bloggerfriendHook)
	case boil.AfterUpdateHook:
		bloggerfriendAfterUpdateHooks = append(bloggerfriendAfterUpdateHooks, bloggerfriendHook)
	case boil.AfterDeleteHook:
		bloggerfriendAfterDeleteHooks = append(bloggerfriendAfterDeleteHooks, bloggerfriendHook)
	case boil.AfterUpsertHook:
		bloggerfriendAfterUpsertHooks = append(bloggerfriendAfterUpsertHooks, bloggerfriendHook)
	}
}

// OneP returns a single bloggerfriend record from the query, and panics on error.
func (q bloggerfriendQuery) OneP() *Bloggerfriend {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single bloggerfriend record from the query.
func (q bloggerfriendQuery) One() (*Bloggerfriend, error) {
	o := &Bloggerfriend{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for bloggerfriend")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Bloggerfriend records from the query, and panics on error.
func (q bloggerfriendQuery) AllP() BloggerfriendSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Bloggerfriend records from the query.
func (q bloggerfriendQuery) All() (BloggerfriendSlice, error) {
	var o []*Bloggerfriend

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Bloggerfriend slice")
	}

	if len(bloggerfriendAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Bloggerfriend records in the query, and panics on error.
func (q bloggerfriendQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Bloggerfriend records in the query.
func (q bloggerfriendQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count bloggerfriend rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q bloggerfriendQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q bloggerfriendQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if bloggerfriend exists")
	}

	return count > 0, nil
}

// BloggerfriendsG retrieves all records.
func BloggerfriendsG(mods ...qm.QueryMod) bloggerfriendQuery {
	return Bloggerfriends(boil.GetDB(), mods...)
}

// Bloggerfriends retrieves all the records using an executor.
func Bloggerfriends(exec boil.Executor, mods ...qm.QueryMod) bloggerfriendQuery {
	mods = append(mods, qm.From("`bloggerfriend`"))
	return bloggerfriendQuery{NewQuery(exec, mods...)}
}

// FindBloggerfriendG retrieves a single record by ID.
func FindBloggerfriendG(blogger int, friend int, selectCols ...string) (*Bloggerfriend, error) {
	return FindBloggerfriend(boil.GetDB(), blogger, friend, selectCols...)
}

// FindBloggerfriendGP retrieves a single record by ID, and panics on error.
func FindBloggerfriendGP(blogger int, friend int, selectCols ...string) *Bloggerfriend {
	retobj, err := FindBloggerfriend(boil.GetDB(), blogger, friend, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindBloggerfriend retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBloggerfriend(exec boil.Executor, blogger int, friend int, selectCols ...string) (*Bloggerfriend, error) {
	bloggerfriendObj := &Bloggerfriend{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `bloggerfriend` where `blogger`=? AND `friend`=?", sel,
	)

	q := queries.Raw(exec, query, blogger, friend)

	err := q.Bind(bloggerfriendObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from bloggerfriend")
	}

	return bloggerfriendObj, nil
}

// FindBloggerfriendP retrieves a single record by ID with an executor, and panics on error.
func FindBloggerfriendP(exec boil.Executor, blogger int, friend int, selectCols ...string) *Bloggerfriend {
	retobj, err := FindBloggerfriend(exec, blogger, friend, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Bloggerfriend) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Bloggerfriend) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Bloggerfriend) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Bloggerfriend) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no bloggerfriend provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bloggerfriendColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	bloggerfriendInsertCacheMut.RLock()
	cache, cached := bloggerfriendInsertCache[key]
	bloggerfriendInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			bloggerfriendColumns,
			bloggerfriendColumnsWithDefault,
			bloggerfriendColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(bloggerfriendType, bloggerfriendMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(bloggerfriendType, bloggerfriendMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `bloggerfriend` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `bloggerfriend` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `bloggerfriend` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, bloggerfriendPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.Exec(cache.query, vals...)
	if err != nil {
		return errors.Wrap(err, "models: unable to insert into bloggerfriend")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.Blogger,
		o.Friend,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for bloggerfriend")
	}

CacheNoHooks:
	if !cached {
		bloggerfriendInsertCacheMut.Lock()
		bloggerfriendInsertCache[key] = cache
		bloggerfriendInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Bloggerfriend record. See Update for
// whitelist behavior description.
func (o *Bloggerfriend) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Bloggerfriend record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Bloggerfriend) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Bloggerfriend, and panics on error.
// See Update for whitelist behavior description.
func (o *Bloggerfriend) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Bloggerfriend.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Bloggerfriend) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	bloggerfriendUpdateCacheMut.RLock()
	cache, cached := bloggerfriendUpdateCache[key]
	bloggerfriendUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			bloggerfriendColumns,
			bloggerfriendPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update bloggerfriend, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `bloggerfriend` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, bloggerfriendPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(bloggerfriendType, bloggerfriendMapping, append(wl, bloggerfriendPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update bloggerfriend row")
	}

	if !cached {
		bloggerfriendUpdateCacheMut.Lock()
		bloggerfriendUpdateCache[key] = cache
		bloggerfriendUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q bloggerfriendQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q bloggerfriendQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for bloggerfriend")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BloggerfriendSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o BloggerfriendSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o BloggerfriendSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BloggerfriendSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bloggerfriendPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `bloggerfriend` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, bloggerfriendPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in bloggerfriend slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Bloggerfriend) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Bloggerfriend) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Bloggerfriend) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Bloggerfriend) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no bloggerfriend provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bloggerfriendColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	bloggerfriendUpsertCacheMut.RLock()
	cache, cached := bloggerfriendUpsertCache[key]
	bloggerfriendUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			bloggerfriendColumns,
			bloggerfriendColumnsWithDefault,
			bloggerfriendColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			bloggerfriendColumns,
			bloggerfriendPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert bloggerfriend, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "bloggerfriend", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `bloggerfriend` WHERE `blogger`=? AND `friend`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(bloggerfriendType, bloggerfriendMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(bloggerfriendType, bloggerfriendMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.Exec(cache.query, vals...)
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for bloggerfriend")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.Blogger,
		o.Friend,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for bloggerfriend")
	}

CacheNoHooks:
	if !cached {
		bloggerfriendUpsertCacheMut.Lock()
		bloggerfriendUpsertCache[key] = cache
		bloggerfriendUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Bloggerfriend record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Bloggerfriend) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Bloggerfriend record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Bloggerfriend) DeleteG() error {
	if o == nil {
		return errors.New("models: no Bloggerfriend provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Bloggerfriend record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Bloggerfriend) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Bloggerfriend record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Bloggerfriend) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Bloggerfriend provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), bloggerfriendPrimaryKeyMapping)
	sql := "DELETE FROM `bloggerfriend` WHERE `blogger`=? AND `friend`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from bloggerfriend")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q bloggerfriendQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q bloggerfriendQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no bloggerfriendQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from bloggerfriend")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o BloggerfriendSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o BloggerfriendSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Bloggerfriend slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o BloggerfriendSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BloggerfriendSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Bloggerfriend slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(bloggerfriendBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bloggerfriendPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `bloggerfriend` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, bloggerfriendPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from bloggerfriend slice")
	}

	if len(bloggerfriendAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Bloggerfriend) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Bloggerfriend) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Bloggerfriend) ReloadG() error {
	if o == nil {
		return errors.New("models: no Bloggerfriend provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Bloggerfriend) Reload(exec boil.Executor) error {
	ret, err := FindBloggerfriend(exec, o.Blogger, o.Friend)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BloggerfriendSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BloggerfriendSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BloggerfriendSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty BloggerfriendSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BloggerfriendSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	bloggerfriends := BloggerfriendSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bloggerfriendPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `bloggerfriend`.* FROM `bloggerfriend` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, bloggerfriendPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&bloggerfriends)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BloggerfriendSlice")
	}

	*o = bloggerfriends

	return nil
}

// BloggerfriendExists checks if the Bloggerfriend row exists.
func BloggerfriendExists(exec boil.Executor, blogger int, friend int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `bloggerfriend` where `blogger`=? AND `friend`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, blogger, friend)
	}

	row := exec.QueryRow(sql, blogger, friend)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if bloggerfriend exists")
	}

	return exists, nil
}

// BloggerfriendExistsG checks if the Bloggerfriend row exists.
func BloggerfriendExistsG(blogger int, friend int) (bool, error) {
	return BloggerfriendExists(boil.GetDB(), blogger, friend)
}

// BloggerfriendExistsGP checks if the Bloggerfriend row exists. Panics on error.
func BloggerfriendExistsGP(blogger int, friend int) bool {
	e, err := BloggerfriendExists(boil.GetDB(), blogger, friend)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// BloggerfriendExistsP checks if the Bloggerfriend row exists. Panics on error.
func BloggerfriendExistsP(exec boil.Executor, blogger int, friend int) bool {
	e, err := BloggerfriendExists(exec, blogger, friend)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
