// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Blogger is an object representing the database table.
type Blogger struct {
	Index    null.Int64  `boil:"index" json:"index,omitempty" toml:"index" yaml:"index,omitempty"`
	ID       string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Nick     null.String `boil:"nick" json:"nick,omitempty" toml:"nick" yaml:"nick,omitempty"`
	DOB      time.Time   `boil:"DOB" json:"DOB" toml:"DOB" yaml:"DOB"`
	Blogname string      `boil:"blogname" json:"blogname" toml:"blogname" yaml:"blogname"`
	Blogskin int64       `boil:"blogskin" json:"blogskin" toml:"blogskin" yaml:"blogskin"`
	Email    string      `boil:"email" json:"email" toml:"email" yaml:"email"`
	Visitor  int64       `boil:"visitor" json:"visitor" toml:"visitor" yaml:"visitor"`
	Intro    null.String `boil:"intro" json:"intro,omitempty" toml:"intro" yaml:"intro,omitempty"`
	Blogs    int64       `boil:"blogs" json:"blogs" toml:"blogs" yaml:"blogs"`
	IP       null.String `boil:"IP" json:"IP,omitempty" toml:"IP" yaml:"IP,omitempty"`
	TS       int64       `boil:"TS" json:"TS" toml:"TS" yaml:"TS"`
	LastLog  time.Time   `boil:"Last_log" json:"Last_log" toml:"Last_log" yaml:"Last_log"`
	LastPost null.Time   `boil:"Last_post" json:"Last_post,omitempty" toml:"Last_post" yaml:"Last_post,omitempty"`
	Activate int64       `boil:"Activate" json:"Activate" toml:"Activate" yaml:"Activate"`
	Reveal   int64       `boil:"Reveal" json:"Reveal" toml:"Reveal" yaml:"Reveal"`
	Userpic  int64       `boil:"userpic" json:"userpic" toml:"userpic" yaml:"userpic"`
	Lang     string      `boil:"lang" json:"lang" toml:"lang" yaml:"lang"`
	Widget   null.String `boil:"widget" json:"widget,omitempty" toml:"widget" yaml:"widget,omitempty"`

	R *bloggerR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L bloggerL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BloggerColumns = struct {
	Index    string
	ID       string
	Nick     string
	DOB      string
	Blogname string
	Blogskin string
	Email    string
	Visitor  string
	Intro    string
	Blogs    string
	IP       string
	TS       string
	LastLog  string
	LastPost string
	Activate string
	Reveal   string
	Userpic  string
	Lang     string
	Widget   string
}{
	Index:    "index",
	ID:       "id",
	Nick:     "nick",
	DOB:      "DOB",
	Blogname: "blogname",
	Blogskin: "blogskin",
	Email:    "email",
	Visitor:  "visitor",
	Intro:    "intro",
	Blogs:    "blogs",
	IP:       "IP",
	TS:       "TS",
	LastLog:  "Last_log",
	LastPost: "Last_post",
	Activate: "Activate",
	Reveal:   "Reveal",
	Userpic:  "userpic",
	Lang:     "lang",
	Widget:   "widget",
}

var BloggerTableColumns = struct {
	Index    string
	ID       string
	Nick     string
	DOB      string
	Blogname string
	Blogskin string
	Email    string
	Visitor  string
	Intro    string
	Blogs    string
	IP       string
	TS       string
	LastLog  string
	LastPost string
	Activate string
	Reveal   string
	Userpic  string
	Lang     string
	Widget   string
}{
	Index:    "blogger.index",
	ID:       "blogger.id",
	Nick:     "blogger.nick",
	DOB:      "blogger.DOB",
	Blogname: "blogger.blogname",
	Blogskin: "blogger.blogskin",
	Email:    "blogger.email",
	Visitor:  "blogger.visitor",
	Intro:    "blogger.intro",
	Blogs:    "blogger.blogs",
	IP:       "blogger.IP",
	TS:       "blogger.TS",
	LastLog:  "blogger.Last_log",
	LastPost: "blogger.Last_post",
	Activate: "blogger.Activate",
	Reveal:   "blogger.Reveal",
	Userpic:  "blogger.userpic",
	Lang:     "blogger.lang",
	Widget:   "blogger.widget",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod  { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var BloggerWhere = struct {
	Index    whereHelpernull_Int64
	ID       whereHelperstring
	Nick     whereHelpernull_String
	DOB      whereHelpertime_Time
	Blogname whereHelperstring
	Blogskin whereHelperint64
	Email    whereHelperstring
	Visitor  whereHelperint64
	Intro    whereHelpernull_String
	Blogs    whereHelperint64
	IP       whereHelpernull_String
	TS       whereHelperint64
	LastLog  whereHelpertime_Time
	LastPost whereHelpernull_Time
	Activate whereHelperint64
	Reveal   whereHelperint64
	Userpic  whereHelperint64
	Lang     whereHelperstring
	Widget   whereHelpernull_String
}{
	Index:    whereHelpernull_Int64{field: "\"blogger\".\"index\""},
	ID:       whereHelperstring{field: "\"blogger\".\"id\""},
	Nick:     whereHelpernull_String{field: "\"blogger\".\"nick\""},
	DOB:      whereHelpertime_Time{field: "\"blogger\".\"DOB\""},
	Blogname: whereHelperstring{field: "\"blogger\".\"blogname\""},
	Blogskin: whereHelperint64{field: "\"blogger\".\"blogskin\""},
	Email:    whereHelperstring{field: "\"blogger\".\"email\""},
	Visitor:  whereHelperint64{field: "\"blogger\".\"visitor\""},
	Intro:    whereHelpernull_String{field: "\"blogger\".\"intro\""},
	Blogs:    whereHelperint64{field: "\"blogger\".\"blogs\""},
	IP:       whereHelpernull_String{field: "\"blogger\".\"IP\""},
	TS:       whereHelperint64{field: "\"blogger\".\"TS\""},
	LastLog:  whereHelpertime_Time{field: "\"blogger\".\"Last_log\""},
	LastPost: whereHelpernull_Time{field: "\"blogger\".\"Last_post\""},
	Activate: whereHelperint64{field: "\"blogger\".\"Activate\""},
	Reveal:   whereHelperint64{field: "\"blogger\".\"Reveal\""},
	Userpic:  whereHelperint64{field: "\"blogger\".\"userpic\""},
	Lang:     whereHelperstring{field: "\"blogger\".\"lang\""},
	Widget:   whereHelpernull_String{field: "\"blogger\".\"widget\""},
}

// BloggerRels is where relationship names are stored.
var BloggerRels = struct {
}{}

// bloggerR is where relationships are stored.
type bloggerR struct {
}

// NewStruct creates a new relationship struct
func (*bloggerR) NewStruct() *bloggerR {
	return &bloggerR{}
}

// bloggerL is where Load methods for each relationship are stored.
type bloggerL struct{}

var (
	bloggerAllColumns            = []string{"index", "id", "nick", "DOB", "blogname", "blogskin", "email", "visitor", "intro", "blogs", "IP", "TS", "Last_log", "Last_post", "Activate", "Reveal", "userpic", "lang", "widget"}
	bloggerColumnsWithoutDefault = []string{"id", "DOB", "blogname", "blogskin", "email"}
	bloggerColumnsWithDefault    = []string{"index", "nick", "visitor", "intro", "blogs", "IP", "TS", "Last_log", "Last_post", "Activate", "Reveal", "userpic", "lang", "widget"}
	bloggerPrimaryKeyColumns     = []string{"index"}
	bloggerGeneratedColumns      = []string{"index"}
)

type (
	// BloggerSlice is an alias for a slice of pointers to Blogger.
	// This should almost always be used instead of []Blogger.
	BloggerSlice []*Blogger
	// BloggerHook is the signature for custom Blogger hook methods
	BloggerHook func(context.Context, boil.ContextExecutor, *Blogger) error

	bloggerQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	bloggerType                 = reflect.TypeOf(&Blogger{})
	bloggerMapping              = queries.MakeStructMapping(bloggerType)
	bloggerPrimaryKeyMapping, _ = queries.BindMapping(bloggerType, bloggerMapping, bloggerPrimaryKeyColumns)
	bloggerInsertCacheMut       sync.RWMutex
	bloggerInsertCache          = make(map[string]insertCache)
	bloggerUpdateCacheMut       sync.RWMutex
	bloggerUpdateCache          = make(map[string]updateCache)
	bloggerUpsertCacheMut       sync.RWMutex
	bloggerUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var bloggerAfterSelectMu sync.Mutex
var bloggerAfterSelectHooks []BloggerHook

var bloggerBeforeInsertMu sync.Mutex
var bloggerBeforeInsertHooks []BloggerHook
var bloggerAfterInsertMu sync.Mutex
var bloggerAfterInsertHooks []BloggerHook

var bloggerBeforeUpdateMu sync.Mutex
var bloggerBeforeUpdateHooks []BloggerHook
var bloggerAfterUpdateMu sync.Mutex
var bloggerAfterUpdateHooks []BloggerHook

var bloggerBeforeDeleteMu sync.Mutex
var bloggerBeforeDeleteHooks []BloggerHook
var bloggerAfterDeleteMu sync.Mutex
var bloggerAfterDeleteHooks []BloggerHook

var bloggerBeforeUpsertMu sync.Mutex
var bloggerBeforeUpsertHooks []BloggerHook
var bloggerAfterUpsertMu sync.Mutex
var bloggerAfterUpsertHooks []BloggerHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Blogger) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bloggerAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Blogger) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bloggerBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Blogger) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bloggerAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Blogger) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bloggerBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Blogger) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bloggerAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Blogger) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bloggerBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Blogger) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bloggerAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Blogger) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bloggerBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Blogger) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bloggerAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBloggerHook registers your hook function for all future operations.
func AddBloggerHook(hookPoint boil.HookPoint, bloggerHook BloggerHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		bloggerAfterSelectMu.Lock()
		bloggerAfterSelectHooks = append(bloggerAfterSelectHooks, bloggerHook)
		bloggerAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		bloggerBeforeInsertMu.Lock()
		bloggerBeforeInsertHooks = append(bloggerBeforeInsertHooks, bloggerHook)
		bloggerBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		bloggerAfterInsertMu.Lock()
		bloggerAfterInsertHooks = append(bloggerAfterInsertHooks, bloggerHook)
		bloggerAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		bloggerBeforeUpdateMu.Lock()
		bloggerBeforeUpdateHooks = append(bloggerBeforeUpdateHooks, bloggerHook)
		bloggerBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		bloggerAfterUpdateMu.Lock()
		bloggerAfterUpdateHooks = append(bloggerAfterUpdateHooks, bloggerHook)
		bloggerAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		bloggerBeforeDeleteMu.Lock()
		bloggerBeforeDeleteHooks = append(bloggerBeforeDeleteHooks, bloggerHook)
		bloggerBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		bloggerAfterDeleteMu.Lock()
		bloggerAfterDeleteHooks = append(bloggerAfterDeleteHooks, bloggerHook)
		bloggerAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		bloggerBeforeUpsertMu.Lock()
		bloggerBeforeUpsertHooks = append(bloggerBeforeUpsertHooks, bloggerHook)
		bloggerBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		bloggerAfterUpsertMu.Lock()
		bloggerAfterUpsertHooks = append(bloggerAfterUpsertHooks, bloggerHook)
		bloggerAfterUpsertMu.Unlock()
	}
}

// OneG returns a single blogger record from the query using the global executor.
func (q bloggerQuery) OneG(ctx context.Context) (*Blogger, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single blogger record from the query.
func (q bloggerQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Blogger, error) {
	o := &Blogger{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for blogger")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Blogger records from the query using the global executor.
func (q bloggerQuery) AllG(ctx context.Context) (BloggerSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Blogger records from the query.
func (q bloggerQuery) All(ctx context.Context, exec boil.ContextExecutor) (BloggerSlice, error) {
	var o []*Blogger

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Blogger slice")
	}

	if len(bloggerAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Blogger records in the query using the global executor
func (q bloggerQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Blogger records in the query.
func (q bloggerQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count blogger rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q bloggerQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q bloggerQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if blogger exists")
	}

	return count > 0, nil
}

// Bloggers retrieves all the records using an executor.
func Bloggers(mods ...qm.QueryMod) bloggerQuery {
	mods = append(mods, qm.From("\"blogger\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"blogger\".*"})
	}

	return bloggerQuery{q}
}

// FindBloggerG retrieves a single record by ID.
func FindBloggerG(ctx context.Context, index null.Int64, selectCols ...string) (*Blogger, error) {
	return FindBlogger(ctx, boil.GetContextDB(), index, selectCols...)
}

// FindBlogger retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBlogger(ctx context.Context, exec boil.ContextExecutor, index null.Int64, selectCols ...string) (*Blogger, error) {
	bloggerObj := &Blogger{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"blogger\" where \"index\"=?", sel,
	)

	q := queries.Raw(query, index)

	err := q.Bind(ctx, exec, bloggerObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from blogger")
	}

	if err = bloggerObj.doAfterSelectHooks(ctx, exec); err != nil {
		return bloggerObj, err
	}

	return bloggerObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Blogger) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Blogger) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no blogger provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bloggerColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	bloggerInsertCacheMut.RLock()
	cache, cached := bloggerInsertCache[key]
	bloggerInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			bloggerAllColumns,
			bloggerColumnsWithDefault,
			bloggerColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, bloggerGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(bloggerType, bloggerMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(bloggerType, bloggerMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"blogger\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"blogger\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into blogger")
	}

	if !cached {
		bloggerInsertCacheMut.Lock()
		bloggerInsertCache[key] = cache
		bloggerInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Blogger record using the global executor.
// See Update for more documentation.
func (o *Blogger) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Blogger.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Blogger) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	bloggerUpdateCacheMut.RLock()
	cache, cached := bloggerUpdateCache[key]
	bloggerUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			bloggerAllColumns,
			bloggerPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, bloggerGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update blogger, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"blogger\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, bloggerPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(bloggerType, bloggerMapping, append(wl, bloggerPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update blogger row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for blogger")
	}

	if !cached {
		bloggerUpdateCacheMut.Lock()
		bloggerUpdateCache[key] = cache
		bloggerUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q bloggerQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q bloggerQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for blogger")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for blogger")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BloggerSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BloggerSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bloggerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"blogger\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, bloggerPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in blogger slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all blogger")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Blogger) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Blogger) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no blogger provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bloggerColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	bloggerUpsertCacheMut.RLock()
	cache, cached := bloggerUpsertCache[key]
	bloggerUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			bloggerAllColumns,
			bloggerColumnsWithDefault,
			bloggerColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			bloggerAllColumns,
			bloggerPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert blogger, could not build update column list")
		}

		ret := strmangle.SetComplement(bloggerAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(bloggerPrimaryKeyColumns))
			copy(conflict, bloggerPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"blogger\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(bloggerType, bloggerMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(bloggerType, bloggerMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert blogger")
	}

	if !cached {
		bloggerUpsertCacheMut.Lock()
		bloggerUpsertCache[key] = cache
		bloggerUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Blogger record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Blogger) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Blogger record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Blogger) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Blogger provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), bloggerPrimaryKeyMapping)
	sql := "DELETE FROM \"blogger\" WHERE \"index\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from blogger")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for blogger")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q bloggerQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q bloggerQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no bloggerQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from blogger")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for blogger")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o BloggerSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BloggerSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(bloggerBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bloggerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"blogger\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, bloggerPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from blogger slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for blogger")
	}

	if len(bloggerAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Blogger) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no Blogger provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Blogger) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBlogger(ctx, exec, o.Index)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BloggerSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty BloggerSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BloggerSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BloggerSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bloggerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"blogger\".* FROM \"blogger\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, bloggerPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BloggerSlice")
	}

	*o = slice

	return nil
}

// BloggerExistsG checks if the Blogger row exists.
func BloggerExistsG(ctx context.Context, index null.Int64) (bool, error) {
	return BloggerExists(ctx, boil.GetContextDB(), index)
}

// BloggerExists checks if the Blogger row exists.
func BloggerExists(ctx context.Context, exec boil.ContextExecutor, index null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"blogger\" where \"index\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, index)
	}
	row := exec.QueryRowContext(ctx, sql, index)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if blogger exists")
	}

	return exists, nil
}

// Exists checks if the Blogger row exists.
func (o *Blogger) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BloggerExists(ctx, exec, o.Index)
}
