// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// Joke is an object representing the database table.
type Joke struct {
	ID  int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	MSG null.String `boil:"msg" json:"msg,omitempty" toml:"msg" yaml:"msg,omitempty"`

	R *jokeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L jokeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var JokeColumns = struct {
	ID  string
	MSG string
}{
	ID:  "id",
	MSG: "msg",
}

// jokeR is where relationships are stored.
type jokeR struct {
}

// jokeL is where Load methods for each relationship are stored.
type jokeL struct{}

var (
	jokeColumns               = []string{"id", "msg"}
	jokeColumnsWithoutDefault = []string{"msg"}
	jokeColumnsWithDefault    = []string{"id"}
	jokePrimaryKeyColumns     = []string{"id"}
)

type (
	// JokeSlice is an alias for a slice of pointers to Joke.
	// This should generally be used opposed to []Joke.
	JokeSlice []*Joke
	// JokeHook is the signature for custom Joke hook methods
	JokeHook func(boil.Executor, *Joke) error

	jokeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	jokeType                 = reflect.TypeOf(&Joke{})
	jokeMapping              = queries.MakeStructMapping(jokeType)
	jokePrimaryKeyMapping, _ = queries.BindMapping(jokeType, jokeMapping, jokePrimaryKeyColumns)
	jokeInsertCacheMut       sync.RWMutex
	jokeInsertCache          = make(map[string]insertCache)
	jokeUpdateCacheMut       sync.RWMutex
	jokeUpdateCache          = make(map[string]updateCache)
	jokeUpsertCacheMut       sync.RWMutex
	jokeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var jokeBeforeInsertHooks []JokeHook
var jokeBeforeUpdateHooks []JokeHook
var jokeBeforeDeleteHooks []JokeHook
var jokeBeforeUpsertHooks []JokeHook

var jokeAfterInsertHooks []JokeHook
var jokeAfterSelectHooks []JokeHook
var jokeAfterUpdateHooks []JokeHook
var jokeAfterDeleteHooks []JokeHook
var jokeAfterUpsertHooks []JokeHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Joke) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range jokeBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Joke) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range jokeBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Joke) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range jokeBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Joke) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range jokeBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Joke) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range jokeAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Joke) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range jokeAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Joke) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range jokeAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Joke) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range jokeAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Joke) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range jokeAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddJokeHook registers your hook function for all future operations.
func AddJokeHook(hookPoint boil.HookPoint, jokeHook JokeHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		jokeBeforeInsertHooks = append(jokeBeforeInsertHooks, jokeHook)
	case boil.BeforeUpdateHook:
		jokeBeforeUpdateHooks = append(jokeBeforeUpdateHooks, jokeHook)
	case boil.BeforeDeleteHook:
		jokeBeforeDeleteHooks = append(jokeBeforeDeleteHooks, jokeHook)
	case boil.BeforeUpsertHook:
		jokeBeforeUpsertHooks = append(jokeBeforeUpsertHooks, jokeHook)
	case boil.AfterInsertHook:
		jokeAfterInsertHooks = append(jokeAfterInsertHooks, jokeHook)
	case boil.AfterSelectHook:
		jokeAfterSelectHooks = append(jokeAfterSelectHooks, jokeHook)
	case boil.AfterUpdateHook:
		jokeAfterUpdateHooks = append(jokeAfterUpdateHooks, jokeHook)
	case boil.AfterDeleteHook:
		jokeAfterDeleteHooks = append(jokeAfterDeleteHooks, jokeHook)
	case boil.AfterUpsertHook:
		jokeAfterUpsertHooks = append(jokeAfterUpsertHooks, jokeHook)
	}
}

// OneP returns a single joke record from the query, and panics on error.
func (q jokeQuery) OneP() *Joke {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single joke record from the query.
func (q jokeQuery) One() (*Joke, error) {
	o := &Joke{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for joke")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Joke records from the query, and panics on error.
func (q jokeQuery) AllP() JokeSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Joke records from the query.
func (q jokeQuery) All() (JokeSlice, error) {
	var o []*Joke

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Joke slice")
	}

	if len(jokeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Joke records in the query, and panics on error.
func (q jokeQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Joke records in the query.
func (q jokeQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count joke rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q jokeQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q jokeQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if joke exists")
	}

	return count > 0, nil
}

// JokesG retrieves all records.
func JokesG(mods ...qm.QueryMod) jokeQuery {
	return Jokes(boil.GetDB(), mods...)
}

// Jokes retrieves all the records using an executor.
func Jokes(exec boil.Executor, mods ...qm.QueryMod) jokeQuery {
	mods = append(mods, qm.From("`joke`"))
	return jokeQuery{NewQuery(exec, mods...)}
}

// FindJokeG retrieves a single record by ID.
func FindJokeG(id int, selectCols ...string) (*Joke, error) {
	return FindJoke(boil.GetDB(), id, selectCols...)
}

// FindJokeGP retrieves a single record by ID, and panics on error.
func FindJokeGP(id int, selectCols ...string) *Joke {
	retobj, err := FindJoke(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindJoke retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindJoke(exec boil.Executor, id int, selectCols ...string) (*Joke, error) {
	jokeObj := &Joke{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `joke` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(jokeObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from joke")
	}

	return jokeObj, nil
}

// FindJokeP retrieves a single record by ID with an executor, and panics on error.
func FindJokeP(exec boil.Executor, id int, selectCols ...string) *Joke {
	retobj, err := FindJoke(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Joke) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Joke) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Joke) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Joke) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no joke provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(jokeColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	jokeInsertCacheMut.RLock()
	cache, cached := jokeInsertCache[key]
	jokeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			jokeColumns,
			jokeColumnsWithDefault,
			jokeColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(jokeType, jokeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(jokeType, jokeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `joke` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `joke` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `joke` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, jokePrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into joke")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == jokeMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for joke")
	}

CacheNoHooks:
	if !cached {
		jokeInsertCacheMut.Lock()
		jokeInsertCache[key] = cache
		jokeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Joke record. See Update for
// whitelist behavior description.
func (o *Joke) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Joke record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Joke) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Joke, and panics on error.
// See Update for whitelist behavior description.
func (o *Joke) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Joke.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Joke) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	jokeUpdateCacheMut.RLock()
	cache, cached := jokeUpdateCache[key]
	jokeUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			jokeColumns,
			jokePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update joke, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `joke` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, jokePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(jokeType, jokeMapping, append(wl, jokePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update joke row")
	}

	if !cached {
		jokeUpdateCacheMut.Lock()
		jokeUpdateCache[key] = cache
		jokeUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q jokeQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q jokeQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for joke")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o JokeSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o JokeSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o JokeSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o JokeSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), jokePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `joke` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, jokePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in joke slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Joke) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Joke) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Joke) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Joke) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no joke provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(jokeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	jokeUpsertCacheMut.RLock()
	cache, cached := jokeUpsertCache[key]
	jokeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			jokeColumns,
			jokeColumnsWithDefault,
			jokeColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			jokeColumns,
			jokePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert joke, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "joke", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `joke` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(jokeType, jokeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(jokeType, jokeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for joke")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == jokeMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for joke")
	}

CacheNoHooks:
	if !cached {
		jokeUpsertCacheMut.Lock()
		jokeUpsertCache[key] = cache
		jokeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Joke record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Joke) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Joke record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Joke) DeleteG() error {
	if o == nil {
		return errors.New("models: no Joke provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Joke record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Joke) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Joke record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Joke) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Joke provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), jokePrimaryKeyMapping)
	sql := "DELETE FROM `joke` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from joke")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q jokeQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q jokeQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no jokeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from joke")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o JokeSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o JokeSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Joke slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o JokeSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o JokeSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Joke slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(jokeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), jokePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `joke` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, jokePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from joke slice")
	}

	if len(jokeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Joke) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Joke) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Joke) ReloadG() error {
	if o == nil {
		return errors.New("models: no Joke provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Joke) Reload(exec boil.Executor) error {
	ret, err := FindJoke(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *JokeSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *JokeSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *JokeSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty JokeSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *JokeSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	jokes := JokeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), jokePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `joke`.* FROM `joke` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, jokePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&jokes)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in JokeSlice")
	}

	*o = jokes

	return nil
}

// JokeExists checks if the Joke row exists.
func JokeExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `joke` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if joke exists")
	}

	return exists, nil
}

// JokeExistsG checks if the Joke row exists.
func JokeExistsG(id int) (bool, error) {
	return JokeExists(boil.GetDB(), id)
}

// JokeExistsGP checks if the Joke row exists. Panics on error.
func JokeExistsGP(id int) bool {
	e, err := JokeExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// JokeExistsP checks if the Joke row exists. Panics on error.
func JokeExistsP(exec boil.Executor, id int) bool {
	e, err := JokeExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
