// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// T is an object representing the database table.
type T struct {
	Blogger int         `boil:"blogger" json:"blogger" toml:"blogger" yaml:"blogger"`
	Title   null.String `boil:"title" json:"title,omitempty" toml:"title" yaml:"title,omitempty"`
	Content null.String `boil:"content" json:"content,omitempty" toml:"content" yaml:"content,omitempty"`
	Addtime time.Time   `boil:"addtime" json:"addtime" toml:"addtime" yaml:"addtime"`
	Cate    int         `boil:"cate" json:"cate" toml:"cate" yaml:"cate"`

	R *tR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TColumns = struct {
	Blogger string
	Title   string
	Content string
	Addtime string
	Cate    string
}{
	Blogger: "blogger",
	Title:   "title",
	Content: "content",
	Addtime: "addtime",
	Cate:    "cate",
}

// tR is where relationships are stored.
type tR struct {
}

// tL is where Load methods for each relationship are stored.
type tL struct{}

var (
	tColumns               = []string{"blogger", "title", "content", "addtime", "cate"}
	tColumnsWithoutDefault = []string{"blogger", "title", "content"}
	tColumnsWithDefault    = []string{"addtime", "cate"}
	tPrimaryKeyColumns     = []string{"blogger"}
)

type (
	// TSlice is an alias for a slice of pointers to T.
	// This should generally be used opposed to []T.
	TSlice []*T
	// THook is the signature for custom T hook methods
	THook func(boil.Executor, *T) error

	tQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tType                 = reflect.TypeOf(&T{})
	tMapping              = queries.MakeStructMapping(tType)
	tPrimaryKeyMapping, _ = queries.BindMapping(tType, tMapping, tPrimaryKeyColumns)
	tInsertCacheMut       sync.RWMutex
	tInsertCache          = make(map[string]insertCache)
	tUpdateCacheMut       sync.RWMutex
	tUpdateCache          = make(map[string]updateCache)
	tUpsertCacheMut       sync.RWMutex
	tUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var tBeforeInsertHooks []THook
var tBeforeUpdateHooks []THook
var tBeforeDeleteHooks []THook
var tBeforeUpsertHooks []THook

var tAfterInsertHooks []THook
var tAfterSelectHooks []THook
var tAfterUpdateHooks []THook
var tAfterDeleteHooks []THook
var tAfterUpsertHooks []THook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *T) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range tBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *T) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range tBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *T) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range tBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *T) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range tBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *T) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range tAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *T) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range tAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *T) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range tAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *T) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range tAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *T) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range tAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTHook registers your hook function for all future operations.
func AddTHook(hookPoint boil.HookPoint, tHook THook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		tBeforeInsertHooks = append(tBeforeInsertHooks, tHook)
	case boil.BeforeUpdateHook:
		tBeforeUpdateHooks = append(tBeforeUpdateHooks, tHook)
	case boil.BeforeDeleteHook:
		tBeforeDeleteHooks = append(tBeforeDeleteHooks, tHook)
	case boil.BeforeUpsertHook:
		tBeforeUpsertHooks = append(tBeforeUpsertHooks, tHook)
	case boil.AfterInsertHook:
		tAfterInsertHooks = append(tAfterInsertHooks, tHook)
	case boil.AfterSelectHook:
		tAfterSelectHooks = append(tAfterSelectHooks, tHook)
	case boil.AfterUpdateHook:
		tAfterUpdateHooks = append(tAfterUpdateHooks, tHook)
	case boil.AfterDeleteHook:
		tAfterDeleteHooks = append(tAfterDeleteHooks, tHook)
	case boil.AfterUpsertHook:
		tAfterUpsertHooks = append(tAfterUpsertHooks, tHook)
	}
}

// OneP returns a single t record from the query, and panics on error.
func (q tQuery) OneP() *T {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single t record from the query.
func (q tQuery) One() (*T, error) {
	o := &T{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for ts")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all T records from the query, and panics on error.
func (q tQuery) AllP() TSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all T records from the query.
func (q tQuery) All() (TSlice, error) {
	var o []*T

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to T slice")
	}

	if len(tAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all T records in the query, and panics on error.
func (q tQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all T records in the query.
func (q tQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count ts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q tQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q tQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if ts exists")
	}

	return count > 0, nil
}

// TSG retrieves all records.
func TSG(mods ...qm.QueryMod) tQuery {
	return TS(boil.GetDB(), mods...)
}

// TS retrieves all the records using an executor.
func TS(exec boil.Executor, mods ...qm.QueryMod) tQuery {
	mods = append(mods, qm.From("`ts`"))
	return tQuery{NewQuery(exec, mods...)}
}

// FindTG retrieves a single record by ID.
func FindTG(blogger int, selectCols ...string) (*T, error) {
	return FindT(boil.GetDB(), blogger, selectCols...)
}

// FindTGP retrieves a single record by ID, and panics on error.
func FindTGP(blogger int, selectCols ...string) *T {
	retobj, err := FindT(boil.GetDB(), blogger, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindT retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindT(exec boil.Executor, blogger int, selectCols ...string) (*T, error) {
	tObj := &T{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `ts` where `blogger`=?", sel,
	)

	q := queries.Raw(exec, query, blogger)

	err := q.Bind(tObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from ts")
	}

	return tObj, nil
}

// FindTP retrieves a single record by ID with an executor, and panics on error.
func FindTP(exec boil.Executor, blogger int, selectCols ...string) *T {
	retobj, err := FindT(exec, blogger, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *T) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *T) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *T) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *T) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no ts provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	tInsertCacheMut.RLock()
	cache, cached := tInsertCache[key]
	tInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			tColumns,
			tColumnsWithDefault,
			tColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(tType, tMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tType, tMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `ts` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `ts` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `ts` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, tPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.Exec(cache.query, vals...)
	if err != nil {
		return errors.Wrap(err, "models: unable to insert into ts")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.Blogger,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for ts")
	}

CacheNoHooks:
	if !cached {
		tInsertCacheMut.Lock()
		tInsertCache[key] = cache
		tInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single T record. See Update for
// whitelist behavior description.
func (o *T) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single T record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *T) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the T, and panics on error.
// See Update for whitelist behavior description.
func (o *T) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the T.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *T) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	tUpdateCacheMut.RLock()
	cache, cached := tUpdateCache[key]
	tUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			tColumns,
			tPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update ts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `ts` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, tPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tType, tMapping, append(wl, tPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update ts row")
	}

	if !cached {
		tUpdateCacheMut.Lock()
		tUpdateCache[key] = cache
		tUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q tQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q tQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for ts")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o TSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o TSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `ts` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in t slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *T) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *T) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *T) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *T) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no ts provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tUpsertCacheMut.RLock()
	cache, cached := tUpsertCache[key]
	tUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			tColumns,
			tColumnsWithDefault,
			tColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			tColumns,
			tPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert ts, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "ts", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `ts` WHERE `blogger`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(tType, tMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tType, tMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.Exec(cache.query, vals...)
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for ts")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.Blogger,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for ts")
	}

CacheNoHooks:
	if !cached {
		tUpsertCacheMut.Lock()
		tUpsertCache[key] = cache
		tUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single T record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *T) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single T record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *T) DeleteG() error {
	if o == nil {
		return errors.New("models: no T provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single T record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *T) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single T record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *T) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no T provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tPrimaryKeyMapping)
	sql := "DELETE FROM `ts` WHERE `blogger`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from ts")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q tQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q tQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no tQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from ts")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o TSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o TSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no T slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o TSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no T slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(tBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `ts` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from t slice")
	}

	if len(tAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *T) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *T) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *T) ReloadG() error {
	if o == nil {
		return errors.New("models: no T provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *T) Reload(exec boil.Executor) error {
	ret, err := FindT(exec, o.Blogger)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty TSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	ts := TSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `ts`.* FROM `ts` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&ts)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TSlice")
	}

	*o = ts

	return nil
}

// TExists checks if the T row exists.
func TExists(exec boil.Executor, blogger int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `ts` where `blogger`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, blogger)
	}

	row := exec.QueryRow(sql, blogger)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if ts exists")
	}

	return exists, nil
}

// TExistsG checks if the T row exists.
func TExistsG(blogger int) (bool, error) {
	return TExists(boil.GetDB(), blogger)
}

// TExistsGP checks if the T row exists. Panics on error.
func TExistsGP(blogger int) bool {
	e, err := TExists(boil.GetDB(), blogger)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// TExistsP checks if the T row exists. Panics on error.
func TExistsP(exec boil.Executor, blogger int) bool {
	e, err := TExists(exec, blogger)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
